// Generated by rustra setup. Requires Rustra 0.12.0 or later.
// Add `mod rustra_setup;` to the native entry. Preserve plugins/state on the builder.

pub fn register<R: tauri::Runtime>(builder: tauri::Builder<R>) -> tauri::Builder<R> {
    rustra::tauri_support::register_with_events(crate::package(), builder)
}

// Use this instead of .invoke_handler(...) when the app also has native commands.
// This must be the final handler installation; Rustra's production endpoints take precedence.
pub fn with_app_commands<R, F>(builder: tauri::Builder<R>, app_handler: F) -> tauri::Builder<R>
where
    R: tauri::Runtime,
    F: Fn(tauri::ipc::Invoke<R>) -> bool + Send + Sync + 'static,
{
    rustra::tauri_support::with_app_commands(register(builder), app_handler)
}
