// AUTO-GENERATED by bun run build:fingerprint. DO NOT EDIT.
export const RUSTRA_BUILD_FINGERPRINT =
  '6843783b416a60f3f6fbb093ceffd55a92bfa95a06d5ce0125836b27aada50bc';
export const RUSTRA_BUILD_INPUT_COUNT = 247;
