// AUTO-GENERATED by bun run build:fingerprint. DO NOT EDIT.
export const RUSTRA_BUILD_FINGERPRINT =
  '8d20cef383f74946a2f71f10fb2103c2f20fca1a0a2b9a3fc1f9b60441876ea2';
export const RUSTRA_BUILD_INPUT_COUNT = 314;
