// AUTO-GENERATED by bun run build:fingerprint. DO NOT EDIT.
export const RUSTRA_BUILD_FINGERPRINT =
  'dc795f520112c6c1f10a218477ebe10f2d2c10030276100bec0fee833acfb7c3';
export const RUSTRA_BUILD_INPUT_COUNT = 220;
