[package]
name = "rustra-calculator-example"
edition.workspace = true
license.workspace = true
version.workspace = true
publish = false

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
rustra.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode = { version = "2", features = ["serde"] }
rmp-serde = "1"
postcard = { version = "1", features = ["alloc"] }
rkyv = { version = "0.8", features = ["bytecheck", "alloc"] }
