/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function rustraInvoke(command: string, argsJson?: string | undefined | null): string

/**
 * Buffer 반환 변형 — String 왕복의 이중 할당(napi가 UTF-16 문자열로 복사)을
 * 피한다. transport-bench 측정에서 napi 브릿지 오버헤드의 대부분이 이 복사라
 * 대형 응답(스키마, 배열) 경로에서 유의미하다. 프레임 형식은 rustra_invoke 와
 * 동일한 JSON — JS 측에서 Buffer.toString()/직접 파싱 어느 쪽이든 소비 가능.
 */
export declare function rustraInvokeBuffer(command: string, argsJson?: string | undefined | null): Buffer

/**
 * 이미 등록된 calculator 패키지로 postcard(rkyv V2) 프레임을 실행한다.
 * 요청/응답 모두 코어 rkyv V2 레이아웃 그대로 — JS 측
 * `createRkyvV2Engine(native, registry)`의 `RkyvV2Native` 계약
 * (`invokeRkyvV2(payload: ArrayBuffer): ArrayBuffer`)과 짝이 맞다.
 *
 * JSON String 왕복(`rustra_invoke`) 대비 UTF-16 복사와 JSON
 * 직렬화/파싱을 모두 건너뛴다 — 코어 실측 61.5ns vs JSON 1.11µs.
 *
 * cargo test 빌드에서 cdylib 진입점이 죽은 코드로 보여 dead_code 경고가
 * 나지만 napi CLI 가 이 심볼을 JS 로 노출한다.
 */
export declare function rustraInvokeRkyvV2(payload: Buffer): Buffer
