[package]
name = "rustra-macros"
description.workspace = true
repository.workspace = true
readme = "README.md"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
rustra = { path = "../rustra" }
serde = { version = "1", features = ["derive"] }
schemars = "0.8"
