export function printHelp(command?: string): void {
  if (command === 'generate') {
    console.log(
      'Usage: rustra generate --schema <path> --output <dir> [options]\n\nOptions:\n  --config <path>     Read schema/output and host settings from rustra.json\n  --schema <path>     Path to schema.json\n  --output <dir>      Generated TypeScript output directory\n  --cpp-output <dir>  Optional C++ codec output directory\n  --positional        Also emit positional-facade.ts\n  --check             Verify generated files without writing\n  --format <fmt>      text (default) or json\n  --help, -h          Show this help message',
    );
    return;
  }
  if (command === 'codegen') {
    console.log(
      'Usage: rustra codegen --config <path> [--check] [--format text|json]\n\nOptions:\n  --config <path>  Path to rustra.json\n  --check          Verify generated files without writing\n  --format <fmt>   text (default) or json\n  --help, -h       Show this help message',
    );
    return;
  }
  if (command === 'init') {
    console.log(
      'Usage: rustra init <dir> [--host <name>] [--force]\n\nOptions:\n  --host <name>    Host section to generate: node (default) or react-native\n  --force          Overwrite existing scaffold files\n  --help, -h       Show this help message',
    );
    return;
  }
  if (command === 'diff') {
    console.log(
      'Usage: rustra diff --old <path> --new <path> [--format text|json]\n\nOptions:\n  --old <path>     Old schema\n  --new <path>     New schema\n  --format <fmt>   text (default) or json\n  --help, -h       Show this help message',
    );
    return;
  }
  if (command === 'doctor') {
    console.log(
      'Usage: rustra doctor [--config <path>] [--format text|json] [--strict]\n\nOptions:\n  --config <path>  Doctor config\n  --format <fmt>   text (default) or json\n  --strict         Treat warnings as failures\n  --help, -h       Show this help message',
    );
    return;
  }
  if (command === 'dev') {
    console.log(
      'Usage: rustra dev [--config <path>] [--backend <dir>] [--app <dir>] [--inspect]\n\nOptions:\n  --config <path>  rustra.json path\n  --backend <dir>  Rust backend directory\n  --app <dir>      App directory containing generated/\n  --inspect        Print devtools instrumentation guidance\n  --help, -h       Show this help message',
    );
    return;
  }
  console.log(`rustra - TypeScript code generation for rustra-bridge

Usage:
  rustra generate --schema <path> --output <dir>
  rustra generate --config <path>
  rustra generate --watch --schema <path> --output <dir>
  rustra codegen --config <path> [--check] [--format text|json]
  rustra init <dir> [--host <name>] [--force]
  rustra diff --old <schema.v1.json> --new <schema.json> [--format json]
  rustra doctor [--config <path>] [--format text|json] [--strict]
  rustra dev [--config <path>] [--backend <dir>] [--app <dir>]

Options:
  --version, -v       Show the installed CLI version
  --schema <path>     Path to schema.json file
  --output <dir>      Output directory for generated TypeScript files
  --cpp-output <dir>  Optional C++ codec output directory
  --positional        Also emit positional-facade.ts
  --config <path>     Path to rustra.json config file
  --watch             Watch schema file for changes and regenerate
  --check             Verify generated bytes without writing
  --format <fmt>      text (default) or json
  --strict             Treat doctor warnings as failures
  --host <name>        Host section for init: node (default) or react-native
  --force              Allow init to overwrite existing files
  --help, -h          Show this help message`);
}
