import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { devInputFingerprint } from './dev-fingerprint.js';
import { withDevGeneratedInputExclusions } from './dev-generated-inputs.js';

test('dev excludes only recorded files, including native outputs outside the TS directory', () => {
  const root = mkdtempSync(join(tmpdir(), 'rustra-dev-generated-inputs-'));
  const outputPath = join(root, 'src');
  const native = join(root, 'native');
  const schemaPath = join(outputPath, 'schema.json');
  const mirror = join(outputPath, 'uniffi_generated.rs');
  const binding = join(outputPath, 'bindings');
  const manifestPath = join(outputPath, '.rustra-generated.json');
  mkdirSync(outputPath);
  mkdirSync(native);
  mkdirSync(binding);
  const owned = [join(outputPath, 'commands.ts'), join(native, 'codecs.hpp')];
  const source = join(outputPath, 'lib.rs');
  writeFileSync(source, 'pub const VALUE: u8 = 1;');
  for (const path of [...owned, schemaPath, mirror, join(binding, 'api.swift')])
    writeFileSync(path, 'original');
  const manifest = {
    schemaVersion: 1,
    files: [
      { path: 'commands.ts', sha256: '0'.repeat(64) },
      { path: '../native/codecs.hpp', sha256: '1'.repeat(64) },
    ],
  };
  writeFileSync(manifestPath, JSON.stringify(manifest));
  try {
    const inputs = () =>
      withDevGeneratedInputExclusions(
        {
          trees: [outputPath, native],
          files: [schemaPath, mirror, owned[1]!, manifestPath],
        },
        { outputPath, schemaPath, uniffiMirrorPath: mirror, uniffiBindingPath: binding },
      );
    const before = devInputFingerprint(inputs());
    for (const path of [...owned, schemaPath, mirror, join(binding, 'api.swift')])
      writeFileSync(path, 'changed generated bytes');
    writeFileSync(manifestPath, JSON.stringify({ ...manifest, schemaHash: 'changed' }));
    assert.equal(
      devInputFingerprint(inputs()),
      before,
      'declared and recorded outputs stay excluded',
    );
    writeFileSync(source, 'pub const VALUE: u8 = 2;');
    assert.notEqual(
      devInputFingerprint(inputs()),
      before,
      'the neighboring handwritten Rust stays visible',
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

for (const [name, manifest] of [
  ['missing', undefined],
  ['malformed', '{invalid'],
  [
    'invalid file ownership',
    JSON.stringify({ schemaVersion: 1, files: [{ path: 'commands.ts', sha256: 'invalid' }] }),
  ],
  [
    'directory ownership',
    JSON.stringify({ schemaVersion: 1, files: [{ path: '.', sha256: '0'.repeat(64) }] }),
  ],
] as const) {
  test(`dev preserves unrecorded files when the ownership manifest is ${name}`, () => {
    const root = mkdtempSync(join(tmpdir(), 'rustra-dev-unrecorded-inputs-'));
    const source = join(root, 'commands.ts');
    const schemaPath = join(root, 'schema.json');
    writeFileSync(source, 'handwritten content');
    if (manifest !== undefined) writeFileSync(join(root, '.rustra-generated.json'), manifest);
    try {
      const inputs = withDevGeneratedInputExclusions(
        { trees: [root], files: [] },
        { outputPath: root, schemaPath },
      );
      const before = devInputFingerprint(inputs);
      writeFileSync(source, 'edited handwritten content');
      assert.notEqual(
        devInputFingerprint(inputs),
        before,
        'familiar generated names confer no ownership',
      );
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
}
