import type { PackageSchema } from './schema.js';
import { commandFunctionName } from './codegen.js';
import {
  collectAllDefinitions,
  collectPostcardFields,
  type PostcardField,
} from './generate-postcard-ir.js';
import { commandCodecSupported } from './generate-postcard.js';
import { POSITIONAL_SCALAR_KINDS } from './generate-routing.js';

/**
 * 패키지 스키마에서 positional facade 파일(`positional-facade.ts`)을 생성한다.
 *
 * 각 정적 명령에 대해:
 * - 입력 필드가 0..3개면 positional 파라미터 시그니처
 * - 그 외는 객체 인자 그대로 pass-through
 * 내부적으로 `installRustraPositional(native)` 로 주입받은 native 의
 * `invokeTyped(name, args)` 를 호출한다 (RN JSI). 코덱 미지원 명령은 생성에서
 * 제외된다 — Tier 3 폴백 경로(commands.ts)를 쓰면 된다.
 */
export function generatePositionalFacadeTs(schema: PackageSchema): string {
  const definitions = collectAllDefinitions(schema);
  const supported = schema.commands.filter((c) => commandCodecSupported(c, definitions));

  let output =
    `// AUTO-GENERATED by @rustra/cli — positional facade (P2).\n` +
    `// 정적 명령을 positional 시그니처로 노출해 JSI invokeTyped 를 직접 호출한다.\n` +
    `// 미지원 명령은 이 파일에 없다 — commands.ts 의 global invoke(Tier 3 폴백 포함) 사용.\n\n`;

  const typeImports = new Set<string>();
  for (const command of supported) {
    if (command.inputType !== '()') typeImports.add(command.inputType);
    if (command.outputType !== '()') typeImports.add(command.outputType);
  }
  const sortedTypeImports = [...typeImports].sort();

  if (sortedTypeImports.length > 0) {
    output += `import type { ${sortedTypeImports.join(', ')} } from './types.js';\n`;
  }
  output += `import type { InvokeOptions } from '@rustra/types';\n\n`;
  output +=
    `/** JSI 네이티브 모듈의 최소 인터페이스 — invokeTypedPos 노출 호스트 권장. */\n` +
    `export type PositionalNative = {\n` +
    `  invokeTyped(name: string, args: unknown): unknown;\n` +
    `  /** (P0-3) cmd_id 진입 — 문자열 마샬링을 건너뛴다. 미노출이면 이름 기반으로 폴백. */\n` +
    `  invokeTypedById?(cmdId: number, args: unknown): unknown;\n` +
    `  /** (Tier 1) positional 진입 — JS 인자 객체 생성/프로퍼티 조회를 통째로 건너뛴다. */\n` +
    `  invokeTypedPos?(cmdId: number, ...fields: unknown[]): unknown;\n` +
    `};\n\n` +
    `let _native: PositionalNative | null = null;\n\n` +
    `/** 앱 시작 시 JSI 네이티브를 주입한다 (installRustraJSI 이후). */\n` +
    `export function installRustraPositional(native: PositionalNative): void {\n` +
    `  _native = native;\n` +
    `}\n\n` +
    `function requireNative(): PositionalNative {\n` +
    `  if (!_native) {\n` +
    `    throw new Error('positional facade not installed — call installRustraPositional(native) first');\n` +
    `  }\n` +
    `  return _native;\n` +
    `}\n\n` +
    `/** byId 진입(우선) — 미노출 구 네이티브는 이름 기반 invokeTyped 로 폴백. */\n` +
    `function call<T>(cmdId: number, name: string, args: unknown): T {\n` +
    `  const native = requireNative();\n` +
    `  if (native.invokeTypedById) {\n` +
    `    return native.invokeTypedById(cmdId, args) as T;\n` +
    `  }\n` +
    `  return native.invokeTyped(name, args) as T;\n` +
    `}\n\n` +
    `/** (Tier 1) positional 진입 — 개별 인자를 그대로 넘긴다(객체 생성 0). */\n` +
    `function callPos<T>(cmdId: number, ...fields: unknown[]): T {\n` +
    `  const native = requireNative();\n` +
    `  if (native.invokeTypedPos) {\n` +
    `    return native.invokeTypedPos(cmdId, ...fields) as T;\n` +
    `  }\n` +
    `  // 구 네이티브 폴백: 필드 순서는 스키마 프로퍼티 순(생성 시점 필드 리스트)과 동일.\n` +
    `  throw new Error(\n` +
    `    'positional entry unavailable — update the native module (invokeTypedPos)',\n` +
    `  );\n` +
    `}\n\n`;

  for (const command of supported) {
    const fnName = commandFunctionName(command.name);
    const outType = command.outputType === '()' ? 'void' : command.outputType;
    const { fields } = collectPostcardFields(command.inputSchema, definitions);
    // 0..3개 필드 → positional; 4+ 또는 nested/option 조합은 객체 인자.
    // POSITIONAL_SCALAR_KINDS는 cppEncodePosCommand와 공유 — 한쪽만 바뀌면
    // facade의 callPos 명령에 C++ 코덱이 없어 런타임 JSError가 난다.
    const positionalKinds = new Set<string>(POSITIONAL_SCALAR_KINDS);
    const simple = fields.every((f) => positionalKinds.has(f.kind));
    const cmdId = command.commandId ?? 0;
    if (fields.length > 0 && fields.length <= 3 && simple) {
      // (Tier 1) 순수 스칼라 필드는 invokeTypedPos 로 — 인자 객체 생성 0.
      const params = fields.map((f) => `${f.name}: ${tsFieldType(f)}`).join(', ');
      const argList = fields.map((f) => `${f.name}`).join(', ');
      output +=
        `export function ${fnName}(${params}, options?: InvokeOptions): Promise<${outType}> {\n` +
        `  void options;\n` +
        `  return Promise.resolve(callPos<${outType}>(${cmdId}, ${argList}));\n` +
        `}\n\n`;
    } else if (fields.length === 0) {
      output +=
        `export function ${fnName}(options?: InvokeOptions): Promise<${outType}> {\n` +
        `  void options;\n` +
        `  return Promise.resolve(call<${outType}>(${cmdId}, '${command.name}', undefined));\n` +
        `}\n\n`;
    } else {
      const inType = command.inputType;
      output +=
        `export function ${fnName}(input: ${inType}, options?: InvokeOptions): Promise<${outType}> {\n` +
        `  void options;\n` +
        `  return Promise.resolve(call<${outType}>(${cmdId}, '${command.name}', input));\n` +
        `}\n\n`;
    }
  }
  return `${output.trimEnd()}\n`;
}

/** 필드의 TS 타입 표현 — input 타입 이름 기반 단순 매핑. */
function tsFieldType(field: PostcardField): string {
  switch (field.kind) {
    case 'zigzag':
      return 'number';
    case 'f64':
    case 'f32':
      return 'number';
    case 'bool':
      return 'boolean';
    case 'string':
      return 'string';
    case 'enum_str':
      return 'string';
    case 'vec_zigzag':
    case 'vec_f64':
      return 'number[]';
    case 'vec_i64':
    case 'vec_u64':
      return '(number | bigint)[]';
    case 'vec_bool':
      return 'boolean[]';
    case 'vec_string':
      return 'string[]';
    case 'set_zigzag':
      return 'Set<number>';
    case 'set_i64':
    case 'set_u64':
      return 'Set<number | bigint>';
    case 'set_f64':
      return 'Set<number>';
    case 'set_bool':
      return 'Set<boolean>';
    case 'set_uvar':
      return 'Set<number>';
    case 'uvar':
    case 'uvar64':
    case 'zigzag64':
      return 'number | bigint';
    case 'bytes':
      return 'Uint8Array | ArrayBuffer';
    case 'vec_uvar':
      return 'number[]';
    case 'map_zigzag':
    case 'map_uvar':
      return 'Record<string, number>';
    case 'map_i64':
    case 'map_u64':
      return 'Record<string, number | bigint>';
    case 'map_f64':
      return 'Record<string, number>';
    case 'map_bool':
      return 'Record<string, boolean>';
    case 'map_string':
      return 'Record<string, string>';
    case 'tuple': {
      const items = field.tupleItems ?? [];
      return `[${items.map((it) => tsFieldType(it)).join(', ')}]`;
    }
    case 'option_zigzag':
    case 'option_uvar':
    case 'option_f64':
    case 'option_f32':
      return 'number | null';
    case 'option_zigzag64':
    case 'option_uvar64':
      return 'number | bigint | null';
    case 'option_bool':
      return 'boolean | null';
    case 'option_string':
      return 'string | null';
    case 'option_struct': {
      const inner: PostcardField = { ...field, kind: 'struct' };
      return `${tsFieldType(inner)} | null`;
    }
    case 'option_bytes':
      return 'Uint8Array | null';
    default:
      return 'unknown';
  }
}
