import type { PackageSchema } from './schema.js';

export function generateRkyvCodecsHpp(_schema: PackageSchema): string {
  return (
    `// AUTO-GENERATED by @rustra/cli — DO NOT EDIT.\n` +
    `// C++ postcard codec for the RN JSI fast path (B1).\n` +
    `// C++는 postcard subset과 Set을 제외한 complex subset을 직접 인코딩/디코딩한다.\n` +
    `// Set을 포함한 complex 명령은 JS codec이 invokeRkyvV2로 전달하고, 동적 명령은\n` +
    `// JS Tier 3 fallback을 사용한다.\n` +
    `#pragma once\n\n` +
    `#include <cstddef>\n#include <cstdint>\n#include <jsi/jsi.h>\n#include <string>\n#include "rustra-codec.hpp"\n\n` +
    `namespace rustra::generated {\n\n` +
    `const facebook::jsi::PropNameID& cachedProp(facebook::jsi::Runtime& rt, const char* name);\n\n` +
    `facebook::jsi::Value make_array_buffer(facebook::jsi::Runtime& rt, const uint8_t* data, size_t size);\n\n` +
    `bool encode_by_name(facebook::jsi::Runtime& rt, const std::string& name, const facebook::jsi::Value& args, rustra::codec::Writer& w);\n` +
    `facebook::jsi::Value decode_by_name(facebook::jsi::Runtime& rt, const std::string& name, rustra::codec::Reader& r);\n\n` +
    `bool encode_by_id(facebook::jsi::Runtime& rt, uint16_t cmd_id, const facebook::jsi::Value& args, rustra::codec::Writer& w);\n` +
    `facebook::jsi::Value decode_by_id(facebook::jsi::Runtime& rt, uint16_t cmd_id, rustra::codec::Reader& r);\n\n` +
    `bool has_static_codec(const std::string& name);\n` +
    `bool has_static_codec_id(uint16_t cmd_id);\n` +
    `bool has_pos_codec(uint16_t cmd_id);\n` +
    `bool has_buffer_codec(uint16_t cmd_id);\n\n` +
    `facebook::jsi::Value decode_buffer_result_by_id(facebook::jsi::Runtime& rt, uint16_t cmd_id, facebook::jsi::Value buffer);\n` +
    `void encode_buffer_by_id(uint16_t cmd_id, const uint8_t* data, size_t size, rustra::codec::Writer& w);\n\n` +
    `void encode_pos_by_id(facebook::jsi::Runtime& rt, uint16_t cmd_id, const facebook::jsi::Value* argv, size_t argc, rustra::codec::Writer& w);\n\n` +
    `bool has_raw_codec(uint16_t cmd_id);\n` +
    `void encode_raw_slots(facebook::jsi::Runtime& rt, uint16_t cmd_id, const facebook::jsi::Value* argv, size_t argc, uint64_t* slots);\n` +
    `facebook::jsi::Value decode_raw_result(facebook::jsi::Runtime& rt, uint16_t cmd_id, uint64_t slot);\n\n` +
    `} // namespace rustra::generated\n`
  );
}
