import assert from 'node:assert/strict';
import { test } from 'bun:test';
import { generateFrameCodecsTs } from './generate-postcard-codec.js';
import { createComplexCodec } from '@rustra/types';
import type { CommandSchema } from './schema.js';

const simple = (name: string, execution?: 'sync' | 'async'): CommandSchema => ({
  name,
  commandId: name === 'add' ? 7 : 8,
  inputType: 'Input',
  outputType: 'Output',
  execution,
  inputSchema: {
    type: 'object',
    properties: { a: { type: 'number' }, b: { type: 'number' } },
    required: ['a', 'b'],
  },
  outputSchema: { type: 'object', properties: { value: { type: 'number' } }, required: ['value'] },
});
function emitted(command: CommandSchema) {
  const source = generateFrameCodecsTs({ packageId: 'test.sync', commands: [command] });
  const javascript = new Bun.Transpiler({ loader: 'ts' }).transformSync(
    source.replace(/^import .*;\n/gm, '').replace(/^export /gm, ''),
  );
  return new Function('createComplexCodec', `${javascript}\nreturn ${command.name}Codec;`)(
    createComplexCodec,
  );
}

test('generated postcard codec keeps producer eligibility and flat field order at runtime', () => {
  const codec = emitted(simple('add', 'sync'));
  assert.equal(codec.execution, 'sync');
  assert.deepEqual(codec.syncFields, ['a', 'b']);
  const bytes = new Uint8Array(codec.encode({ a: 2, b: 3 }));
  assert.equal(bytes[0], 7);
  assert.equal(emitted(simple('later', 'async')).execution, 'async');
  assert.equal(emitted(simple('legacy')).execution, undefined);
});

test('generated complex codec keeps eligibility without pretending complex input is positional', () => {
  const command = simple('groups', 'sync');
  command.inputSchema = {
    type: 'object',
    properties: {
      groups: {
        type: 'object',
        additionalProperties: { type: 'array', items: { type: 'string' } },
      },
    },
    required: ['groups'],
  };
  command.outputSchema = command.inputSchema;
  const codec = emitted(command);
  assert.equal(codec.execution, 'sync');
  assert.equal(codec.syncFields, undefined);
  assert.ok(codec.encode({ groups: { team: ['one', 'two'] } }).byteLength > 2);
});

test('generated bytes route metadata only marks a required single byte field', () => {
  const command = simple('bytes', 'sync');
  command.inputSchema = {
    type: 'object',
    properties: { data: { type: 'array', items: { type: 'integer', format: 'uint8' } } },
    required: ['data'],
  };
  const codec = emitted(command);
  assert.equal(codec.syncByteField, 'data');
});
