#!/usr/bin/env node
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { basename, resolve, dirname, relative } from 'node:path';
import { existsSync, watch, readFileSync, readdirSync, statSync, realpathSync } from 'node:fs';
import { execFileSync, execSync, spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import type { PackageSchema } from './schema.js';
import {
  generateTypesTs,
  generateCommandsTs,
  generateEventsTs,
  generateContractTs,
  generateRkyvCodecsTs,
  generateRkyvRegistryTs,
  generateRkyvCodecsHpp,
  generateRkyvCodecsCpp,
  generatePositionalFacadeTs,
} from './generate.js';
import { diffSchemas, formatDiffResult } from './schema-diff.js';
import {
  GENERATED_REACT_NATIVE_PACKAGE,
  writeReactNativeModule,
  type ReactNativeScaffoldOptions,
} from './react-native.js';
import {
  collectDoctorReport,
  doctorExitCode,
  formatDoctorJson,
  formatDoctorText,
  parseDoctorArgs,
} from './doctor.js';

export { generatePositionalFacadeTs };
export {
  generateTypesTs,
  generateCommandsTs,
  generateEventsTs,
  generateContractTs,
  generateRkyvCodecsTs,
  generateRkyvRegistryTs,
  generateRkyvCodecsHpp,
  generateRkyvCodecsCpp,
} from './generate.js';
export type { PackageSchema, CommandSchema, JsonSchema } from './schema.js';
export { diffSchemas, formatDiffResult } from './schema-diff.js';
export type { BreakingChange, DiffResult } from './schema-diff.js';
export { createValidatedEngine } from './validate-engine.js';
export type { EngineClient as ValidateEngineClient, ValidateOptions } from './validate-engine.js';
export { rustraPlugin } from './vite.js';
export type { RustraVitePluginOptions } from './vite.js';
export { GENERATED_REACT_NATIVE_PACKAGE, renderReactNativeModule } from './react-native.js';
export type { ReactNativeScaffoldOptions } from './react-native.js';
export { parsePackageSchema };

/** dist 레이아웃: dist/index.js 와 package.json 이 같은 레벨(packages/cli)이다.
 * bin/main 모두 ./dist/index.js 이므로 require('../package.json') = packages/cli/package.json.
 * 읽기에 실패하면 조용히 넘기지 않고 즉시 throw — 잘못된 버전의 템플릿을
 * 생성하는 것보다 init 이 크게 실패하는 편이 낫다. */
interface CliManifest {
  version: string;
  dependencies: { '@rustra/types': string };
  rustraTemplate: { cargoRange: string; reactNativeRange: string };
}

const cliManifest = createRequire(import.meta.url)('../package.json') as CliManifest;
const cliVersion = cliManifest.version;

/** CLI, types npm package, and Rust crates have independent versions.
 * The scaffold records each package's own compatible dependency range instead
 * of deriving a Cargo version from the CLI npm version. */
export function templateVersions(
  cliVersion: string,
  npmTypesRange: string,
  cargoRange: string,
): {
  cargoRange: string;
  npmCliCaret: string;
  npmTypesRange: string;
} {
  if (!npmTypesRange.trim() || !cargoRange.trim()) {
    throw new Error('Rustra compatibility ranges must be non-empty');
  }
  return { cargoRange, npmCliCaret: `^${cliVersion}`, npmTypesRange };
}

export interface InitProjectFiles {
  cargoToml: string;
  libRs: string;
  mainRs: string;
  generateRs: string;
  packageJson: string;
  rustraJson: string;
}

/** `rustra init`의 순수 렌더 단계. 테스트가 실제로 실행 가능한 scaffold 계약을
 * 파일 쓰기나 process.exit 없이 검증할 수 있게 분리한다. */
export function renderInitProjectFiles(v: ReturnType<typeof templateVersions>): InitProjectFiles {
  const cargoToml = `# Generated by rustra init — adjust name/edition as needed.
[package]
name = "rustra-app"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "rustra-app"

[dependencies]
rustra = "${v.cargoRange}"
rustra-macros = "${v.cargoRange}"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = "0.8"

[[bin]]
name = "generate"
path = "src/bin/generate.rs"
`;

  const libRs = `use rustra::prelude::*;

#[derive(Debug, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct EchoInput {
    pub message: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct EchoOutput {
    pub message: String,
}

#[rustra::command]
fn echo(input: EchoInput) -> Result<EchoOutput> {
    Ok(EchoOutput {
        message: input.message,
    })
}

pub fn package() -> Package {
    Package::builder("app.demo").command_fn(echo).build()
}
`;

  const mainRs = `fn main() -> rustra::Result<()> {
    let result = rustra_app::package().invoke_json(
        "echo",
        serde_json::json!({ "message": "hello from rustra" }),
    )?;
    println!("{}", result["message"].as_str().unwrap_or_default());
    Ok(())
}
`;

  const generateRs = `fn main() -> rustra::Result<()> {
    let generated = rustra_app::package().generate_typescript()?;
    generated.write_to_dir("generated")?;
    println!("generated/schema.json written");
    Ok(())
}
`;

  const packageJson = `{
  "name": "rustra-app",
  "private": true,
  "packageManager": "bun@1.4.0",
  "type": "module",
  "scripts": {
    "doctor": "rustra doctor --config rustra.json",
    "codegen": "rustra codegen --config rustra.json",
    "codegen:check": "rustra codegen --config rustra.json --check",
    "dev": "rustra dev --config rustra.json"
  },
  "devDependencies": {
    "@rustra/cli": "${v.npmCliCaret}",
    "@rustra/types": "${v.npmTypesRange}"
  }
}
`;

  const rustraJson = `{
  "schema": "./generated/schema.json",
  "output": "./src/generated",
  "codegen": {
    "rustManifest": "./Cargo.toml",
    "rustBinary": "generate"
  }
}
`;

  return { cargoToml, libRs, mainRs, generateRs, packageJson, rustraJson };
}

/** React Native 전용 zero-boilerplate 진입점. 이 모듈에서 명령을 import하면
 * 첫 호출이 JSI 설치, contract 검증, fast engine configure를 한 번만 수행한다. */
export function generateReactNativeEntryTs(): string {
  const moduleLiteral = JSON.stringify(GENERATED_REACT_NATIVE_PACKAGE);
  return `// AUTO-GENERATED by @rustra/cli — DO NOT EDIT.
import { createRustraBootstrap } from '@rustra/react-native';
import { installRustraJSI, getRustraNative } from ${moduleLiteral};
import { GENERATED_CONTRACT_HASH, SCHEMA_VERSION } from './contract.js';
import { rkyvV2Registry } from './rkyv-registry.js';

export * from './commands.js';
export { subscribeEvent } from '@rustra/react-native';

export const rustra = createRustraBootstrap({
  install: installRustraJSI,
  getNative: getRustraNative,
  rkyvV2Codecs: rkyvV2Registry,
  contractHash: GENERATED_CONTRACT_HASH,
  schemaVersion: SCHEMA_VERSION,
});
`;
}

type CargoHostEntry = {
  targetDirectoryUrl: string;
  targetName: string;
};

export function generateNodeEntryTs(entry: CargoHostEntry & { args?: string[] }): string {
  return `// AUTO-GENERATED by @rustra/cli — DO NOT EDIT.
import { fileURLToPath } from 'node:url';
import { createNodeBootstrap } from '@rustra/node';

export * from './commands.js';

const targetDirectory = new URL(${JSON.stringify(entry.targetDirectoryUrl)}, import.meta.url);
const executable = ${JSON.stringify(entry.targetName)} + (process.platform === 'win32' ? '.exe' : '');

export const rustra = createNodeBootstrap({
  binaryName: ${JSON.stringify(entry.targetName)},
  commandCandidates: [
    fileURLToPath(new URL(\`release/\${executable}\`, targetDirectory)),
    fileURLToPath(new URL(\`debug/\${executable}\`, targetDirectory)),
  ],
  args: ${JSON.stringify(entry.args ?? ['invoke'])},
});
`;
}

export function generateBunEntryTs(entry: CargoHostEntry): string {
  return `// AUTO-GENERATED by @rustra/cli — DO NOT EDIT.
import { fileURLToPath } from 'node:url';
import { suffix } from 'bun:ffi';
import { createBunBootstrap } from '@rustra/bun';
import { GENERATED_CONTRACT_HASH, SCHEMA_VERSION } from './contract.js';
import { rkyvV2Registry } from './rkyv-registry.js';

export * from './commands.js';

const targetDirectory = new URL(${JSON.stringify(entry.targetDirectoryUrl)}, import.meta.url);
const library = \`\${process.platform === 'win32' ? '' : 'lib'}${entry.targetName}.\${suffix}\`;

export const rustra = createBunBootstrap({
  libraryName: ${JSON.stringify(entry.targetName)},
  libraryCandidates: [
    fileURLToPath(new URL(\`release/\${library}\`, targetDirectory)),
    fileURLToPath(new URL(\`debug/\${library}\`, targetDirectory)),
  ],
  rkyvV2Codecs: rkyvV2Registry,
  contractHash: GENERATED_CONTRACT_HASH,
  schemaVersion: SCHEMA_VERSION,
});
`;
}

export function generateTauriEntryTs(): string {
  return `// AUTO-GENERATED by @rustra/cli — DO NOT EDIT.
import { createTauriBootstrap } from '@rustra/tauri';

export * from './commands.js';
export { subscribeTauriEvent as subscribeEvent } from '@rustra/tauri';

export const rustra = createTauriBootstrap();
`;
}

/** TS 식별자로 안전한 문자열만 허용 — 생성 코드에 그대로 삽입되는 이름의
 * 주입 방어. $ 허용은 JS 식별자 규격 준수. */
const TS_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function assertIdentifier(value: string, where: string): void {
  if (!TS_IDENTIFIER.test(value)) {
    throw new Error(
      `Invalid schema: ${where} must be a plain identifier, got: ${JSON.stringify(value)}`,
    );
  }
}

/**
 * 스키마 트리 전체의 식별자 화이트리스트 — 코드젠이 식별자 위치(따옴표 없이
 * 방출하는 이름)에 삽입하는 모든 키를 검증한다:
 * - `definitions` 키(최상위 cmd.definitions 외에 inputSchema/outputSchema 내부,
 *   다른 definition 내부의 중첩 definitions 포함 — collectDefinitionsInner 가
 *   재귀 수집해 `export type ${name}` 으로 방출)
 * - `properties` 키(생성 TS 멤버 `${name}:`, rkyv 코덱 `args.${name}`,
 *   C++ `getProperty(rt, "${name}")` — 모두 무인용 방출)
 * - `$ref` 대상 타입명(resolveRef 로 벗겨 타입 위치에 방출)
 *
 * schemars/serde 는 Rust 필드명(식별자)만 내보내므로 정상 스키마는 영향 없다.
 * description/enum 값 등 자유 문자열은 여기서 거부하지 않는다 — 방출 시점
 * 이스케이프(codegen.ts escapeJsDoc/escapeStringLiteral)로 방어한다.
 */
function assertSchemaIdentifiers(
  schema: unknown,
  where: string,
  visited: Set<unknown> = new Set(),
): void {
  if (typeof schema !== 'object' || schema === null || visited.has(schema)) return;
  visited.add(schema);
  const node = schema as {
    definitions?: Record<string, unknown>;
    properties?: Record<string, unknown>;
    $ref?: unknown;
    [key: string]: unknown;
  };
  if (typeof node.$ref === 'string') {
    const target = node.$ref.replace(/^#\/(definitions\/|\$defs\/)/, '');
    assertIdentifier(target, `${where} $ref target`);
  }
  if (node.definitions) {
    for (const key of Object.keys(node.definitions)) {
      assertIdentifier(key, `${where} definitions key`);
      assertSchemaIdentifiers(node.definitions[key], `${where}.${key}`, visited);
    }
  }
  if (node.properties) {
    for (const key of Object.keys(node.properties)) {
      assertIdentifier(key, `${where} property name`);
      assertSchemaIdentifiers(node.properties[key], `${where}.${key}`, visited);
    }
  }
  // collectDefinitionsInner 의 순회와 동일한 하위 스키마 위치을 따라간다.
  for (const arrayKey of ['anyOf', 'oneOf', 'allOf', 'prefixItems'] as const) {
    const arr = node[arrayKey];
    if (Array.isArray(arr)) {
      for (let i = 0; i < arr.length; i++) {
        assertSchemaIdentifiers(arr[i], `${where}.${arrayKey}[${i}]`, visited);
      }
    }
  }
  const items = node.items;
  if (Array.isArray(items)) {
    items.forEach((s, i) => assertSchemaIdentifiers(s, `${where}.items[${i}]`, visited));
  } else if (items) {
    assertSchemaIdentifiers(items, `${where}.items`, visited);
  }
  if (
    node.additionalProperties &&
    typeof node.additionalProperties === 'object' &&
    !Array.isArray(node.additionalProperties)
  ) {
    assertSchemaIdentifiers(node.additionalProperties, `${where}.additionalProperties`, visited);
  }
}

/** import 로 main() 이 실행되지 않도록 진입점 판별 — 테스트가 ./index.js 를
 * import 해도 CLI 가 실행되지 않는다. bin 스크립트(node dist/index.js)와
 * `node src/index.ts` 직접 실행 양쪽 모두 진입점으로 취급한다. */
function isCliEntry(): boolean {
  if (!process.argv[1]) return false;
  try {
    return realpathSync(resolve(process.argv[1])) === fileURLToPath(import.meta.url);
  } catch {
    return false;
  }
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);

  if (args.length === 0 || args[0] === '--help' || args[0] === '-h') {
    printHelp();
    process.exit(0);
  }

  if (args[0] === 'generate') {
    const rest = args.slice(1);
    if (rest.includes('--watch')) {
      await runWatch(rest.filter((a) => a !== '--watch'));
      return;
    }
    await runGenerate(rest);
    return;
  }

  if (args[0] === 'codegen') {
    await runCodegen(args.slice(1));
    return;
  }

  if (args[0] === 'init') {
    await runInit(args.slice(1));
    return;
  }

  if (args[0] === 'diff') {
    await runDiff(args.slice(1));
    return;
  }

  if (args[0] === 'doctor') {
    await runDoctor(args.slice(1));
    return;
  }

  if (args[0] === 'dev') {
    const { runDev } = await import('./dev.js');
    await runDev(args.slice(1));
    return;
  }

  console.error(`Unknown command: ${args[0]}`);
  console.error('Run "rustra --help" for usage information.');
  process.exit(1);
}

/** `rustra doctor [--config rustra.json] [--format text|json] [--strict]`. */
export async function runDoctor(args: string[]): Promise<void> {
  const options = parseDoctorArgs(args);
  const report = collectDoctorReport({
    configPath: resolve(options.configPath),
    strict: options.strict,
  });
  console.log(options.format === 'json' ? formatDoctorJson(report) : formatDoctorText(report));
  process.exitCode = doctorExitCode(report, options.strict);
}

interface CodegenOptions {
  configPath?: string;
  check?: boolean;
}

function parseCodegenArgs(args: string[]): CodegenOptions {
  const options: CodegenOptions = {};
  for (let index = 0; index < args.length; index += 1) {
    switch (args[index]) {
      case '--config':
        options.configPath = args[++index];
        break;
      case '--check':
        options.check = true;
        break;
      default:
        throw new Error(`Unknown codegen option: ${args[index]}`);
    }
  }
  if (!options.configPath) throw new Error('codegen requires --config <path>');
  return options;
}

function spawnInherit(cmd: string, args: string[], cwd: string): Promise<void> {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(cmd, args, { cwd, stdio: 'inherit' });
    child.on('error', reject);
    child.on('exit', (code, signal) => {
      if (code === 0) {
        resolvePromise();
      } else {
        reject(new Error(`${cmd} ${signal ? `terminated by ${signal}` : `exit ${code}`}`));
      }
    });
  });
}

export function selectCodegenBinary(
  targets: Array<{ name: string; kind?: string[]; crate_types?: string[] }>,
  requested?: string,
): string {
  const binaries = targets.filter(
    (target) => target.kind?.includes('bin') || target.crate_types?.includes('bin'),
  );
  const selected = requested
    ? binaries.find((target) => target.name === requested)
    : binaries.find((target) => target.name === 'generate') ??
      (binaries.length === 1 ? binaries[0] : undefined);
  if (!selected) {
    const names = binaries.map((target) => target.name).sort().join(', ') || 'none';
    throw new Error(`codegen.rust_binary_ambiguous: found ${names}; set codegen.rustBinary`);
  }
  return selected.name;
}

export async function runCodegen(args: string[]): Promise<void> {
  const options = parseCodegenArgs(args);
  const configPath = resolve(options.configPath!);
  const config = readConfigSync(configPath);
  const target = resolveCodegenTarget(configPath, config);
  console.log(
    `[rustra] Rust schema: cargo run --manifest-path ${target.manifestPath} ` +
      `--package ${target.packageName} --bin ${target.binaryName}`,
  );
  await spawnInherit(
    'cargo',
    [
      'run',
      '--quiet',
      '--manifest-path',
      target.manifestPath,
      '--package',
      target.packageName,
      '--bin',
      target.binaryName,
    ],
    target.cwd,
  );
  console.log(`[rustra] TypeScript/C++: generate --config ${configPath}`);
  await runGenerate(['--config', configPath, ...(options.check ? ['--check'] : [])]);
}

/**
 * `rustra diff --old a.json --new b.json [--format json]` — 스키마 버전 간
 * breaking change 검출. breaking 이 있으면 exit 1 (CI 게이트용).
 */
async function runDiff(args: string[]): Promise<void> {
  const getOpt = (name: string): string | undefined => {
    const i = args.indexOf(`--${name}`);
    return i >= 0 ? args[i + 1] : undefined;
  };
  const oldPath = getOpt('old');
  const newPath = getOpt('new');
  const asJson = args.includes('--format') && args[args.indexOf('--format') + 1] === 'json';

  if (!oldPath || !newPath) {
    console.error(
      'Error: --old and --new are required. Usage: rustra diff --old v1.json --new v2.json',
    );
    process.exit(1);
  }

  const [oldRaw, newRaw] = await Promise.all([
    readFile(resolve(oldPath), 'utf-8'),
    readFile(resolve(newPath), 'utf-8'),
  ]);
  const result = diffSchemas(
    parsePackageSchema(JSON.parse(oldRaw)),
    parsePackageSchema(JSON.parse(newRaw)),
  );

  if (asJson) {
    console.log(JSON.stringify(result, null, 2));
  } else {
    console.log(formatDiffResult(result));
    if (result.compatible.length > 0) {
      console.log(`Compatible additions (${result.compatible.length}):`);
      for (const c of result.compatible) console.log(`  + ${c}`);
    }
  }

  if (result.breaking.length > 0) process.exit(1);
}

/**
 * `rustra init <dir>` — 프로젝트 스캐폴딩.
 *
 * 최소 동작 구조를 생성한다: Cargo 크레이트(의존성은 버전 지정 — crates.io 발행 기준),
 * lib.rs 의 공유 패키지 정의, 실제 generate bin, package.json(codegen 스크립트),
 * rustra.json(CLI 설정)을 만든다.
 */
async function runInit(args: string[]): Promise<void> {
  const dir = args.find((a) => !a.startsWith('--'));
  if (!dir) {
    console.error('Error: Provide a project directory. Usage: rustra init my-project');
    process.exit(1);
  }
  const root = resolve(dir);
  const versions = templateVersions(
    cliVersion,
    cliManifest.dependencies['@rustra/types'],
    cliManifest.rustraTemplate.cargoRange,
  );
  const files = renderInitProjectFiles(versions);

  await mkdir(resolve(root, 'src/bin'), { recursive: true });
  await writeFile(resolve(root, 'Cargo.toml'), files.cargoToml);
  await writeFile(resolve(root, 'src/lib.rs'), files.libRs);
  await writeFile(resolve(root, 'src/main.rs'), files.mainRs);
  await writeFile(resolve(root, 'src/bin/generate.rs'), files.generateRs);
  await writeFile(resolve(root, 'package.json'), files.packageJson);
  await writeFile(resolve(root, 'rustra.json'), files.rustraJson);

  console.log(`Created rustra project in ${root}:`);
  console.log(
    '  Cargo.toml, src/lib.rs, src/main.rs, src/bin/generate.rs, package.json, rustra.json',
  );
  console.log('\nNext steps:');
  console.log('  cd ' + dir);
  console.log('  bun install');
  console.log('  bun run codegen      # schema + complete TS client');
  console.log('  cargo run            # invokes the generated echo command');
}

function printHelp(): void {
  console.log(`rustra - TypeScript code generation for rustra-bridge

Usage:
  rustra generate --schema <path> --output <dir>
  rustra generate --schema <path> --output <dir> --cpp-output <dir>
  rustra generate --config <path>
  rustra generate --watch --schema <path> --output <dir>
  rustra codegen --config <path> [--check]
  rustra init <dir>
  rustra diff --old <schema.v1.json> --new <schema.json> [--format json]
  rustra doctor [--config <path>] [--format text|json] [--strict]
  rustra dev [--backend <dir>] [--app <dir>]

Options:
  --schema <path>    Path to schema.json file
  --output <dir>     Output directory for generated TypeScript files
  --cpp-output <dir> Optional: also emit C++ codec (rustra-generated-codecs.{hpp,cpp})
                    for the RN JSI fast path (B1) into this directory
  --positional       Also emit positional-facade.ts (P2) — direct invokeTyped wrappers
  --config <path>    Path to rustra.json config file
  --watch            Watch schema file for changes and regenerate
  --check            (generate/codegen) verify generated bytes without writing TS/C++/RN files
  --old <path>       (diff) old schema version to compare from
  --new <path>       (diff) new schema version to compare against
  --format <fmt>     (diff) 'text' (default) or 'json' (machine-readable DiffResult)
  --format <fmt>     (doctor) 'text' (default) or 'json' (machine-readable DoctorReport)
  --strict           (doctor) treat warnings as failures
  --backend <dir>    (dev) Rust backend crate dir (default: ./backend)
  --app <dir>        (dev) App dir containing generated/ (default: ./app)
  --inspect          (dev) codegen tick 후 @rustra/devtools 계측 안내 출력
  --help, -h         Show this help message

Examples:
  rustra generate --schema ./generated/schema.json --output ./src/generated
  rustra generate --watch --config rustra.json
  rustra generate --schema ./gen/schema.json --output ./src/generated --cpp-output ./ios
  rustra generate --config rustra.json  # includes React Native when configured
  rustra codegen --config rustra.json
  rustra diff --old ./generated/schema.v1.json --new ./generated/schema.json
  rustra doctor --config rustra.json --format json
  rustra dev --backend ./backend --app ./app
`);
}

interface GenerateOptions {
  schemaPath?: string;
  outputPath?: string;
  configPath?: string;
  cppOutputPath?: string;
  /** (P2) positional-facade.ts 추가 생성 — RN JSI invokeTyped 직접 호출 래퍼. */
  positional?: boolean;
  check?: boolean;
}

export async function runGenerate(args: string[]): Promise<void> {
  autoRebuild();
  const { schemaPath, outputPath, cppOutputPath, positional, reactNativeScaffold, hostEntries } =
    resolvePaths(args);
  const written = await generateFromSchema(
    schemaPath,
    outputPath,
    cppOutputPath,
    positional,
    reactNativeScaffold,
    hostEntries,
  );
  console.log(`Generated TypeScript files in ${outputPath}:`);
  for (const f of written) console.log(`  ${f}`);
}

function resolvePaths(args: string[]): {
  schemaPath: string;
  outputPath: string;
  cppOutputPath?: string;
  positional?: boolean;
  reactNativeScaffold?: ReactNativeScaffoldOptions;
  hostEntries?: HostEntries;
} {
  const options = parseGenerateArgs(args);

  let schemaPath: string;
  let outputPath: string;
  let config: RustraConfig | undefined;

  if (options.configPath) {
    config = readConfigSync(options.configPath);
    schemaPath = resolve(dirname(options.configPath), config.schema);
    outputPath = resolve(dirname(options.configPath), config.output);
  } else if (options.schemaPath && options.outputPath) {
    schemaPath = options.schemaPath;
    outputPath = options.outputPath;
  } else {
    console.error('Error: Provide --schema and --output, or --config with a config file.');
    process.exit(1);
  }

  const reactNativeScaffold = config?.reactNative
    ? resolveReactNativeScaffold(config, options.configPath!)
    : undefined;
  const cppOutputPath = options.cppOutputPath
    ? resolve(options.cppOutputPath)
    : config?.cppOutput
      ? resolve(dirname(options.configPath!), config.cppOutput)
      : reactNativeScaffold?.cppOutputPath;
  const resolvedOutputPath = resolve(outputPath);
  const hostEntries = config
    ? resolveHostEntries(config, options.configPath!, resolvedOutputPath)
    : undefined;

  return {
    schemaPath: resolve(schemaPath),
    outputPath: resolvedOutputPath,
    cppOutputPath,
    positional: options.positional ?? config?.positional,
    reactNativeScaffold: reactNativeScaffold
      ? { ...reactNativeScaffold, cppOutputPath: cppOutputPath! }
      : undefined,
    hostEntries,
  };
}

async function runWatch(args: string[]): Promise<void> {
  const { schemaPath, outputPath, cppOutputPath, positional, reactNativeScaffold, hostEntries } =
    resolvePaths(args);

  await generateFromSchema(
    schemaPath,
    outputPath,
    cppOutputPath,
    positional,
    reactNativeScaffold,
    hostEntries,
  );
  console.log(`\nWatching ${schemaPath} for changes...`);

  let debounceTimer: ReturnType<typeof setTimeout> | null = null;
  watch(dirname(schemaPath), (_event, filename) => {
    if (!filename || !filename.endsWith('.json')) return;
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(async () => {
      try {
        await generateFromSchema(
          schemaPath,
          outputPath,
          cppOutputPath,
          positional,
          reactNativeScaffold,
          hostEntries,
        );
        console.log(`[${new Date().toLocaleTimeString()}] Regenerated`);
      } catch (error) {
        console.error(`Regeneration failed: ${error instanceof Error ? error.message : error}`);
      }
    }, 100);
  });
}

async function generateFromSchema(
  schemaPath: string,
  outputPath: string,
  cppOutputPath?: string,
  positional = false,
  reactNativeScaffold?: ReactNativeScaffoldOptions,
  hostEntries?: HostEntries,
): Promise<string[]> {
  const schemaContent = await readFile(schemaPath, 'utf-8');
  const schema: PackageSchema = parsePackageSchema(JSON.parse(schemaContent));

  // 필드 순서 일관성 경고 — properties 가 알파벳 순으로 정렬돼 있으면 postcard
  // 선언 순서 가정이 깨질 가능성이 있다(과거 schemars 비-preserve_order 산출물).
  // 단순 우연 정렬(calculator 의 a,b 같은 짧은 세트)은 흔하므로, 스키마 전체에서
  // 정렬 징후가 반복될 때(≥3개 명령) 한 번만 요약 경고를 낸다.
  if (schema.fieldOrder !== 'declaration') {
    let sortedFieldSuspects = 0;
    for (const command of schema.commands) {
      for (const s of [command.inputSchema, command.outputSchema]) {
        const names = Object.keys(s.properties ?? {});
        const sorted = [...names].sort();
        if (names.length > 1 && JSON.stringify(names) === JSON.stringify(sorted)) {
          sortedFieldSuspects++;
        }
      }
    }
    if (sortedFieldSuspects >= 3) {
      console.warn(
        `[rustra] WARN: ${sortedFieldSuspects} field sets appear alphabetically sorted and ` +
          `the schema has no fieldOrder=declaration guarantee; postcard encodes in Rust ` +
          `declaration order — regenerate with current rustra or verify field order manually.`,
      );
    }
  }

  const files: { name: string; content: string }[] = [
    { name: 'types.ts', content: generateTypesTs(schema) },
    { name: 'commands.ts', content: generateCommandsTs(schema) },
    { name: 'contract.ts', content: generateContractTs(schemaContent) },
    { name: 'rkyv-codecs.ts', content: generateRkyvCodecsTs(schema) },
    { name: 'rkyv-registry.ts', content: generateRkyvRegistryTs(schema) },
  ];

  // (이벤트 계약) 선언된 이벤트가 있을 때만 events.ts 를 만든다 — 없으면
  // 산출물 목록이 기존과 동일(하위호환).
  const eventsTs = generateEventsTs(schema);
  if (eventsTs) {
    files.push({ name: 'events.ts', content: eventsTs });
  }

  if (positional) {
    files.push({ name: 'positional-facade.ts', content: generatePositionalFacadeTs(schema) });
  }

  if (reactNativeScaffold) {
    files.push({ name: 'react-native.ts', content: generateReactNativeEntryTs() });
  }
  if (hostEntries?.node) {
    files.push({ name: 'node.ts', content: generateNodeEntryTs(hostEntries.node) });
  }
  if (hostEntries?.bun) {
    files.push({ name: 'bun.ts', content: generateBunEntryTs(hostEntries.bun) });
  }
  if (hostEntries?.tauri) {
    files.push({ name: 'tauri.ts', content: generateTauriEntryTs() });
  }

  if (cppOutputPath) {
    files.push({ name: 'rustra-generated-codecs.hpp', content: generateRkyvCodecsHpp(schema) });
    files.push({ name: 'rustra-generated-codecs.cpp', content: generateRkyvCodecsCpp(schema) });
  }

  const written: string[] = [];
  // TS 출력은 outputPath 로, C++ 출력은 cppOutputPath 로 분리.
  for (const { name, content } of files) {
    const targetDir = name.endsWith('.hpp') || name.endsWith('.cpp') ? cppOutputPath! : outputPath;
    const filePath = resolve(targetDir, name);
    let existing: string | null = null;
    try {
      existing = await readFile(filePath, 'utf-8');
    } catch {
      /* file doesn't exist */
    }
    if (existing === content) {
      written.push(`${name} (unchanged)`);
    } else {
      await mkdir(dirname(filePath), { recursive: true });
      await writeFile(filePath, content);
      written.push(existing !== null ? `${name} (updated)` : name);
    }
  }
  if (cppOutputPath) {
    await mkdir(cppOutputPath, { recursive: true });
  }
  if (reactNativeScaffold) {
    const moduleFiles = await writeReactNativeModule(reactNativeScaffold);
    await ensureReactNativeDependency(
      reactNativeScaffold.appRoot,
      reactNativeScaffold.moduleDir,
      reactNativeScaffold.adapterRange,
    );
    written.push(...moduleFiles.map((name) => `native/${name}`));
  }
  if (hostEntries) {
    await ensureHostDependencies(hostEntries);
  }
  return written;
}

/**
 * Auto-rebuild the CLI if source files are newer than dist.
 * Prevents running a stale binary that generates outdated code.
 */
function autoRebuild(): void {
  try {
    const cliDir = resolve(dirname(new URL(import.meta.url).pathname), '..');
    const srcDir = resolve(cliDir, 'src');
    const distDir = resolve(cliDir, 'dist');

    let newestSrc = 0;
    let oldestDist = Infinity;
    const srcFiles = readdirSync(srcDir).filter((f: string) => f.endsWith('.ts'));
    for (const f of srcFiles) {
      const stat = statSync(resolve(srcDir, f));
      if (stat.mtimeMs > newestSrc) newestSrc = stat.mtimeMs;
    }
    try {
      const distFiles = readdirSync(distDir).filter((f: string) => f.endsWith('.js'));
      for (const f of distFiles) {
        const stat = statSync(resolve(distDir, f));
        if (stat.mtimeMs < oldestDist) oldestDist = stat.mtimeMs;
      }
    } catch {
      // dist doesn't exist yet — need build
      oldestDist = 0;
    }

    if (newestSrc > oldestDist) {
      console.log('CLI source is newer than dist — rebuilding...');
      execSync('bun run build', { cwd: cliDir, stdio: 'pipe' });
      console.log('CLI rebuilt.');
    }
  } catch {
    // Auto-rebuild is best-effort — don't block generate on failure
  }
}

function parseGenerateArgs(args: string[]): GenerateOptions {
  const options: GenerateOptions = {};

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--schema':
        options.schemaPath = args[++i];
        break;
      case '--output':
        options.outputPath = args[++i];
        break;
      case '--cpp-output':
        options.cppOutputPath = args[++i];
        break;
      case '--config':
        options.configPath = args[++i];
        break;
      case '--positional':
        options.positional = true;
        break;
      case '--check':
        options.check = true;
        break;
    }
  }

  return options;
}

interface RustraConfig {
  schema: string;
  output: string;
  cppOutput?: string;
  positional?: boolean;
  codegen?: {
    rustManifest?: string;
    rustPackage?: string;
    rustBinary?: string;
  };
  reactNative?: {
    moduleDir?: string;
    rustManifest?: string;
    rustPackage?: string;
    rustLibrary?: string;
    legacyBenchmarks?: boolean;
  };
  node?: {
    rustManifest?: string;
    rustPackage?: string;
    rustBinary?: string;
    args?: string[];
  };
  bun?: {
    rustManifest?: string;
    rustPackage?: string;
    rustLibrary?: string;
  };
  tauri?: Record<string, never>;
}

type CargoMetadata = {
  target_directory?: string;
  packages: Array<{
    name: string;
    manifest_path: string;
    targets: Array<{
      name: string;
      crate_types: string[];
      kind?: string[];
    }>;
  }>;
};

export function resolveCodegenTarget(
  configPath: string,
  config: RustraConfig,
): { manifestPath: string; packageName: string; binaryName: string; cwd: string } {
  const cwd = dirname(resolve(configPath));
  const manifestPath = config.codegen?.rustManifest
    ? resolve(cwd, config.codegen.rustManifest)
    : findCargoManifest(cwd);
  if (!manifestPath) {
    throw new Error('codegen.rust_manifest_missing: set codegen.rustManifest in rustra.json');
  }
  const metadata = readCargoMetadata(manifestPath);
  const candidates = config.codegen?.rustPackage
    ? metadata.packages.filter((candidate) => candidate.name === config.codegen?.rustPackage)
    : metadata.packages.filter((candidate) => resolve(candidate.manifest_path) === resolve(manifestPath));
  if (candidates.length !== 1) {
    const names = candidates.map((candidate) => candidate.name).sort().join(', ') || 'none';
    throw new Error(
      `codegen.rust_package_ambiguous: found ${names}; set codegen.rustPackage`,
    );
  }
  const packageInfo = candidates[0]!;
  return {
    manifestPath: resolve(manifestPath),
    packageName: packageInfo.name,
    binaryName: selectCodegenBinary(packageInfo.targets, config.codegen?.rustBinary),
    cwd,
  };
}

type HostEntries = {
  appRoot: string;
  node?: CargoHostEntry & { args?: string[] };
  bun?: CargoHostEntry;
  tauri?: true;
};

export function selectReactNativeCargoTarget(
  metadata: CargoMetadata,
  manifestPath: string,
  requestedPackage?: string,
): { rustPackage: string; rustLibrary: string } {
  const manifest = resolve(manifestPath);
  const manifestPackages = metadata.packages.filter(
    (candidate) => resolve(candidate.manifest_path) === manifest,
  );
  const candidates = requestedPackage
    ? metadata.packages.filter((candidate) => candidate.name === requestedPackage)
    : manifestPackages.length > 0
      ? manifestPackages
      : metadata.packages.filter((candidate) =>
          candidate.targets.some((target) => target.crate_types.includes('staticlib')),
        );

  if (candidates.length !== 1) {
    const names =
      candidates
        .map((candidate) => candidate.name)
        .sort()
        .join(', ') || 'none';
    throw new Error(
      requestedPackage
        ? `Cargo package ${requestedPackage} was not found uniquely in ${manifestPath}`
        : `React Native setup found ${candidates.length} static-library crates (${names}). ` +
            'Point rustManifest at the app crate, or set reactNative.rustPackage.',
    );
  }

  const selected = candidates[0]!;
  const staticLibraries = selected.targets.filter((target) =>
    target.crate_types.includes('staticlib'),
  );
  if (staticLibraries.length !== 1) {
    throw new Error(
      `Cargo package ${selected.name} must expose exactly one staticlib target. ` +
        'Add crate-type = ["rlib", "staticlib"] under [lib].',
    );
  }
  return { rustPackage: selected.name, rustLibrary: staticLibraries[0]!.name };
}

function readCargoMetadata(manifestPath: string): CargoMetadata {
  try {
    const CARGO_TOML = realpathSync(resolve(manifestPath));
    if (basename(CARGO_TOML) !== 'Cargo.toml' || !statSync(CARGO_TOML).isFile()) {
      throw new Error('rustManifest must point to a regular Cargo.toml file');
    }
    const CARGO_METADATA_ARGS = [
      'metadata',
      '--format-version',
      '1',
      '--no-deps',
      '--manifest-path',
      CARGO_TOML,
    ];
    const cargoOutput = execFileSync('cargo', CARGO_METADATA_ARGS, { encoding: 'utf8' });
    return JSON.parse(cargoOutput) as CargoMetadata;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Could not inspect ${manifestPath} with cargo metadata: ${message}`, {
      cause: error,
    });
  }
}

function readCargoTarget(manifestPath: string, requestedPackage?: string) {
  const metadata = readCargoMetadata(manifestPath);
  return selectReactNativeCargoTarget(metadata, manifestPath, requestedPackage);
}

function selectHostPackage(
  metadata: CargoMetadata,
  manifestPath: string,
  requestedPackage: string | undefined,
) {
  const manifest = resolve(manifestPath);
  const candidates = requestedPackage
    ? metadata.packages.filter((candidate) => candidate.name === requestedPackage)
    : metadata.packages.filter((candidate) => resolve(candidate.manifest_path) === manifest);
  if (candidates.length !== 1) {
    const names =
      candidates
        .map((candidate) => candidate.name)
        .sort()
        .join(', ') || 'none';
    throw new Error(
      requestedPackage
        ? `Cargo package ${requestedPackage} was not found uniquely in ${manifestPath}`
        : `Host setup found ${candidates.length} Cargo packages (${names}). ` +
            'Point rustManifest at the app crate, or set the host rustPackage.',
    );
  }
  return candidates[0]!;
}

function requireTargetDirectory(metadata: CargoMetadata): string {
  if (!metadata.target_directory) {
    throw new Error('cargo metadata did not return target_directory');
  }
  return resolve(metadata.target_directory);
}

function resolveHostEntries(
  config: RustraConfig,
  configPath: string,
  outputPath: string,
): HostEntries | undefined {
  if (!config.node && !config.bun && !config.tauri) return undefined;
  const appRoot = dirname(resolve(configPath));
  const entries: HostEntries = { appRoot };

  if (config.node) {
    const manifest = config.node.rustManifest
      ? resolve(appRoot, config.node.rustManifest)
      : findCargoManifest(appRoot);
    if (!manifest) {
      throw new Error('Node setup could not find Cargo.toml. Set node.rustManifest.');
    }
    const metadata = readCargoMetadata(manifest);
    const cargoPackage = selectHostPackage(metadata, manifest, config.node.rustPackage);
    const binaries = cargoPackage.targets.filter(
      (target) => target.kind?.includes('bin') || target.crate_types.includes('bin'),
    );
    const selected = config.node.rustBinary
      ? binaries.find((target) => target.name === config.node!.rustBinary)
      : (binaries.find((target) => target.name === cargoPackage.name) ??
        (binaries.length === 1 ? binaries[0] : undefined));
    if (!selected) {
      throw new Error(
        `Node setup could not select one Cargo binary from ${binaries
          .map((target) => target.name)
          .sort()
          .join(', ')}. Set node.rustBinary.`,
      );
    }
    entries.node = {
      targetDirectoryUrl: `${portablePackagePath(outputPath, requireTargetDirectory(metadata))}/`,
      targetName: selected.name,
      args: config.node.args,
    };
  }

  if (config.bun) {
    const manifest = config.bun.rustManifest
      ? resolve(appRoot, config.bun.rustManifest)
      : findCargoManifest(appRoot);
    if (!manifest) {
      throw new Error('Bun setup could not find Cargo.toml. Set bun.rustManifest.');
    }
    const metadata = readCargoMetadata(manifest);
    const cargoPackage = selectHostPackage(metadata, manifest, config.bun.rustPackage);
    const libraries = cargoPackage.targets.filter((target) =>
      target.crate_types.includes('cdylib'),
    );
    const selected = config.bun.rustLibrary
      ? libraries.find((target) => target.name === config.bun!.rustLibrary)
      : libraries.length === 1
        ? libraries[0]
        : undefined;
    if (!selected) {
      throw new Error(
        `Bun setup requires one Cargo cdylib (${libraries
          .map((target) => target.name)
          .sort()
          .join(', ')}). Add crate-type = ["rlib", "cdylib"], or set bun.rustLibrary.`,
      );
    }
    entries.bun = {
      targetDirectoryUrl: `${portablePackagePath(outputPath, requireTargetDirectory(metadata))}/`,
      targetName: selected.name,
    };
  }

  if (config.tauri) entries.tauri = true;
  return entries;
}

function findCargoManifest(start: string): string | undefined {
  let current = resolve(start);
  while (true) {
    const candidate = resolve(current, 'Cargo.toml');
    if (existsSync(candidate)) return candidate;
    const parent = dirname(current);
    if (parent === current) return undefined;
    current = parent;
  }
}

function resolveReactNativeScaffold(
  config: RustraConfig,
  configPath: string,
): ReactNativeScaffoldOptions {
  const rn = config.reactNative!;
  const appRoot = dirname(resolve(configPath));
  const moduleDir = resolve(appRoot, rn.moduleDir ?? 'modules/rustra-bridge');
  if (moduleDir !== appRoot && !moduleDir.startsWith(`${appRoot}/`)) {
    throw new Error('Config reactNative.moduleDir must stay inside the app directory');
  }
  const rustManifestPath = rn.rustManifest
    ? resolve(appRoot, rn.rustManifest)
    : findCargoManifest(appRoot);
  if (!rustManifestPath) {
    throw new Error(
      'React Native setup could not find Cargo.toml. Set reactNative.rustManifest in rustra.json.',
    );
  }
  const inferred = readCargoTarget(rustManifestPath, rn.rustPackage);
  const rustPackage = inferred.rustPackage;
  const rustLibrary = rn.rustLibrary ?? inferred.rustLibrary;
  return {
    appRoot,
    moduleDir,
    cppOutputPath: config.cppOutput
      ? resolve(appRoot, config.cppOutput)
      : resolve(moduleDir, 'generated'),
    rustManifestPath,
    rustPackage,
    rustLibrary,
    adapterRange: cliManifest.rustraTemplate.reactNativeRange,
    legacyBenchmarks: rn.legacyBenchmarks,
  };
}

async function ensureReactNativeDependency(
  appRoot: string,
  moduleDir: string,
  adapterRange: string,
): Promise<void> {
  const manifestPath = resolve(appRoot, 'package.json');
  let raw: string;
  try {
    raw = await readFile(manifestPath, 'utf8');
  } catch {
    throw new Error(
      'React Native setup requires package.json next to rustra.json so autolinking can see the generated module.',
    );
  }
  const manifest = JSON.parse(raw) as Record<string, unknown> & {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
    workspaces?: string[];
  };
  const dependencies = { ...(manifest.dependencies ?? {}) };
  const modulePath = portablePackagePath(appRoot, moduleDir);
  const workspacePath = modulePath.replace(/^\.\//, '');
  const expectedModule = 'workspace:*';
  const previousGeneratedModule = `file:${modulePath}`;
  const existingModule = dependencies[GENERATED_REACT_NATIVE_PACKAGE];
  if (
    existingModule !== undefined &&
    existingModule !== expectedModule &&
    existingModule !== previousGeneratedModule
  ) {
    throw new Error(
      `Dependency ${GENERATED_REACT_NATIVE_PACKAGE} already points to ${existingModule}; ` +
        `refusing to replace it with the generated workspace at ${workspacePath}.`,
    );
  }
  dependencies[GENERATED_REACT_NATIVE_PACKAGE] = expectedModule;
  if (
    dependencies['@rustra/react-native'] === undefined &&
    manifest.devDependencies?.['@rustra/react-native'] === undefined
  ) {
    dependencies['@rustra/react-native'] = adapterRange;
  }
  manifest.dependencies = Object.fromEntries(
    Object.entries(dependencies).sort(([a], [b]) => a.localeCompare(b)),
  );
  const workspaces = manifest.workspaces ?? [];
  if (!Array.isArray(workspaces) || workspaces.some((entry) => typeof entry !== 'string')) {
    throw new Error('React Native setup requires package.json workspaces to be a string array');
  }
  if (!workspaces.includes(workspacePath)) {
    manifest.workspaces = [...workspaces, workspacePath].sort();
  }
  const next = `${JSON.stringify(manifest, null, 2)}\n`;
  if (next !== raw) await writeFile(manifestPath, next);
}

async function ensureHostDependencies(hosts: HostEntries): Promise<void> {
  const manifestPath = resolve(hosts.appRoot, 'package.json');
  let raw: string;
  try {
    raw = await readFile(manifestPath, 'utf8');
  } catch {
    throw new Error('Node, Bun, and Tauri setup requires package.json next to rustra.json.');
  }
  const manifest = JSON.parse(raw) as Record<string, unknown> & {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };
  const dependencies = { ...(manifest.dependencies ?? {}) };
  const required = [
    '@rustra/types',
    ...(hosts.node ? ['@rustra/node'] : []),
    ...(hosts.bun ? ['@rustra/bun'] : []),
    ...(hosts.tauri ? ['@rustra/tauri'] : []),
  ];
  const expected = `^${cliVersion}`;
  for (const name of required) {
    const existing = dependencies[name] ?? manifest.devDependencies?.[name];
    if (
      existing !== undefined &&
      existing !== expected &&
      !existing.startsWith('file:') &&
      !existing.startsWith('workspace:')
    ) {
      throw new Error(
        `Dependency ${name} already points to ${existing}; refusing to replace it with ${expected}. ` +
          'Align the Rustra release line explicitly.',
      );
    }
    if (existing === undefined) dependencies[name] = expected;
  }
  manifest.dependencies = Object.fromEntries(
    Object.entries(dependencies).sort(([a], [b]) => a.localeCompare(b)),
  );
  const next = `${JSON.stringify(manifest, null, 2)}\n`;
  if (next !== raw) await writeFile(manifestPath, next);
}

function portablePackagePath(from: string, to: string): string {
  const path = relative(from, to).split('\\').join('/');
  return path.startsWith('.') ? path : `./${path}`;
}

function readConfigSync(configPath: string): RustraConfig {
  const content = readFileSync(resolve(configPath), 'utf-8');
  const config = JSON.parse(content) as RustraConfig;

  if (!config.schema || !config.output) {
    throw new Error(
      'Config file must have "schema" and "output" fields. Example:\n' +
        '{\n  "schema": "./generated/schema.json",\n  "output": "./src/generated"\n}',
    );
  }
  const codegen = config.codegen;
  if (codegen !== undefined) {
    if (typeof codegen !== 'object' || codegen === null || Array.isArray(codegen)) {
      throw new Error('Config codegen must be an object');
    }
    if (
      codegen.rustManifest !== undefined &&
      (typeof codegen.rustManifest !== 'string' ||
        codegen.rustManifest.length === 0 ||
        /[\0\r\n]/.test(codegen.rustManifest))
    ) {
      throw new Error('Config codegen.rustManifest must be a non-empty safe path');
    }
    for (const field of ['rustPackage', 'rustBinary'] as const) {
      const value = codegen[field];
      if (value !== undefined && (typeof value !== 'string' || !/^[A-Za-z0-9_-]+$/.test(value))) {
        throw new Error(`Config codegen.${field} must be a Cargo identifier`);
      }
    }
  }
  const rn = config.reactNative;
  if (rn !== undefined) {
    if (typeof rn !== 'object' || rn === null || Array.isArray(rn)) {
      throw new Error('Config reactNative must be an object');
    }
    if ('nativeModule' in rn) {
      throw new Error(
        'Config reactNative.nativeModule was removed. Use the generated @rustra/generated-react-native module.',
      );
    }
    if (
      rn.rustPackage !== undefined &&
      (typeof rn.rustPackage !== 'string' || !/^[A-Za-z0-9_-]+$/.test(rn.rustPackage))
    ) {
      throw new Error('Config reactNative.rustPackage must be a Cargo package name');
    }
    if (
      rn.rustLibrary !== undefined &&
      (typeof rn.rustLibrary !== 'string' || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(rn.rustLibrary))
    ) {
      throw new Error('Config reactNative.rustLibrary must be a static-library identifier');
    }
    for (const [key, path] of [
      ['moduleDir', rn.moduleDir],
      ['rustManifest', rn.rustManifest],
    ] as const) {
      if (
        path !== undefined &&
        (typeof path !== 'string' || path.length === 0 || /[\0\r\n]/.test(path))
      ) {
        throw new Error(`Config reactNative.${key} must be a non-empty safe path`);
      }
    }
    if (rn.legacyBenchmarks !== undefined && typeof rn.legacyBenchmarks !== 'boolean') {
      throw new Error('Config reactNative.legacyBenchmarks must be a boolean');
    }
  }

  for (const [host, value] of [
    ['node', config.node],
    ['bun', config.bun],
    ['tauri', config.tauri],
  ] as const) {
    if (
      value !== undefined &&
      (typeof value !== 'object' || value === null || Array.isArray(value))
    ) {
      throw new Error(`Config ${host} must be an object`);
    }
  }
  for (const [host, value] of [
    ['node', config.node],
    ['bun', config.bun],
  ] as const) {
    if (!value) continue;
    if (
      value.rustManifest !== undefined &&
      (typeof value.rustManifest !== 'string' ||
        value.rustManifest.length === 0 ||
        /[\0\r\n]/.test(value.rustManifest))
    ) {
      throw new Error(`Config ${host}.rustManifest must be a non-empty safe path`);
    }
    if (
      value.rustPackage !== undefined &&
      (typeof value.rustPackage !== 'string' || !/^[A-Za-z0-9_-]+$/.test(value.rustPackage))
    ) {
      throw new Error(`Config ${host}.rustPackage must be a Cargo package name`);
    }
  }
  if (
    config.node?.rustBinary !== undefined &&
    (typeof config.node.rustBinary !== 'string' || !/^[A-Za-z0-9_-]+$/.test(config.node.rustBinary))
  ) {
    throw new Error('Config node.rustBinary must be a Cargo binary name');
  }
  if (
    config.node?.args !== undefined &&
    (!Array.isArray(config.node.args) ||
      config.node.args.some(
        (arg) => typeof arg !== 'string' || arg.length === 0 || /[\0\r\n]/.test(arg),
      ))
  ) {
    throw new Error('Config node.args must be an array of non-empty safe strings');
  }
  if (
    config.bun?.rustLibrary !== undefined &&
    (typeof config.bun.rustLibrary !== 'string' ||
      !/^[A-Za-z_][A-Za-z0-9_]*$/.test(config.bun.rustLibrary))
  ) {
    throw new Error('Config bun.rustLibrary must be a cdylib identifier');
  }
  if (config.tauri && Object.keys(config.tauri).length > 0) {
    throw new Error('Config tauri currently accepts only an empty object');
  }

  return config;
}

function parsePackageSchema(value: unknown): PackageSchema {
  if (typeof value !== 'object' || value === null) {
    throw new Error('Invalid schema: expected an object');
  }
  const obj = value as Record<string, unknown>;
  if (typeof obj.packageId !== 'string') {
    throw new Error('Invalid schema: missing or invalid "packageId"');
  }
  if (!Array.isArray(obj.commands)) {
    throw new Error('Invalid schema: missing or invalid "commands" array');
  }
  if (obj.fieldOrder !== undefined && obj.fieldOrder !== 'declaration') {
    throw new Error('Invalid schema: "fieldOrder" must be "declaration" when provided');
  }
  for (let i = 0; i < obj.commands.length; i++) {
    const cmd = obj.commands[i] as Record<string, unknown>;
    if (typeof cmd.name !== 'string') {
      throw new Error(`Invalid schema: commands[${i}].name must be a string`);
    }
    if (typeof cmd.inputType !== 'string' || typeof cmd.outputType !== 'string') {
      throw new Error(`Invalid schema: commands[${i}] must have inputType and outputType`);
    }
    if (typeof cmd.inputSchema !== 'object' || typeof cmd.outputSchema !== 'object') {
      throw new Error(`Invalid schema: commands[${i}] must have inputSchema and outputSchema`);
    }
    // 식별자 화이트리스트 — name/inputType/outputType/definitions 키는 생성 TS 에
    // 그대로 삽입되므로 변조 schema.json 통한 코드 주입을 차단한다.
    // '()' 은 unit 타입 센티넬(generate.ts 의 `command.inputType !== '()'` 와 동일).
    assertIdentifier(cmd.name, `commands[${i}].name`);
    if (cmd.inputType !== '()') {
      assertIdentifier(cmd.inputType, `commands[${i}].inputType`);
    }
    if (cmd.outputType !== '()') {
      assertIdentifier(cmd.outputType, `commands[${i}].outputType`);
    }
    if (cmd.definitions) {
      for (const key of Object.keys(cmd.definitions)) {
        assertIdentifier(key, `commands[${i}].definitions key`);
      }
    }
    // 중첩 definitions 키 / 속성명 / $ref 대상도 재귀 검증 — collectDefinitionsInner
    // 가 수집하는 모든 정의와 tsObjectFromSchema 가 무인용 방출하는 모든 필드명.
    assertSchemaIdentifiers(cmd.inputSchema, `commands[${i}].inputSchema`);
    assertSchemaIdentifiers(cmd.outputSchema, `commands[${i}].outputSchema`);
    if (cmd.definitions) {
      for (const [key, def] of Object.entries(cmd.definitions)) {
        assertSchemaIdentifiers(def, `commands[${i}].definitions.${key}`);
      }
    }
  }
  return value as PackageSchema;
}

if (isCliEntry()) {
  main().catch((error) => {
    console.error('Error:', error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
