import { GENERATED_REACT_NATIVE_PACKAGE } from './react-native.js';
import type { CargoHostEntry } from './host-entries.js';

export function generateReactNativeEntryTs(): string {
  const moduleLiteral = JSON.stringify(GENERATED_REACT_NATIVE_PACKAGE);
  return `// AUTO-GENERATED by @rustra/cli — DO NOT EDIT.
import { createRustraBootstrap } from '@rustra/react-native';
import { installRustraJSI, getRustraNative } from ${moduleLiteral};
import { GENERATED_CONTRACT_HASH, SCHEMA_VERSION } from './contract.js';
import { rkyvV2Registry } from './rkyv-registry.js';

export * from './commands.js';
export { subscribeEvent } from '@rustra/react-native';

export const rustra = createRustraBootstrap({
  install: installRustraJSI,
  getNative: getRustraNative,
  rkyvV2Codecs: rkyvV2Registry,
  contractHash: GENERATED_CONTRACT_HASH,
  schemaVersion: SCHEMA_VERSION,
});
`;
}

export function generateNodeEntryTs(entry: CargoHostEntry & { args?: string[] }): string {
  return `// AUTO-GENERATED by @rustra/cli — DO NOT EDIT.
import { fileURLToPath } from 'node:url';
import { createNodeBootstrap } from '@rustra/node';
import { GENERATED_CONTRACT_HASH } from './contract.js';

export * from './commands.js';

const targetDirectory = new URL(${JSON.stringify(entry.targetDirectoryUrl)}, import.meta.url);
const executable = ${JSON.stringify(entry.targetName)} + (process.platform === 'win32' ? '.exe' : '');

export const rustra = createNodeBootstrap({
  binaryName: ${JSON.stringify(entry.targetName)},
  commandCandidates: [
    fileURLToPath(new URL(\`release/\${executable}\`, targetDirectory)),
    fileURLToPath(new URL(\`debug/\${executable}\`, targetDirectory)),
  ],
  args: ${JSON.stringify(entry.args ?? ['invoke'])},
  contractHash: GENERATED_CONTRACT_HASH,
});
`;
}

export function generateBunEntryTs(entry: CargoHostEntry): string {
  return `// AUTO-GENERATED by @rustra/cli — DO NOT EDIT.
import { fileURLToPath } from 'node:url';
import { suffix } from 'bun:ffi';
import { createBunBootstrap } from '@rustra/bun';
import { GENERATED_CONTRACT_HASH, SCHEMA_VERSION } from './contract.js';
import { rkyvV2Registry } from './rkyv-registry.js';

export * from './commands.js';

const targetDirectory = new URL(${JSON.stringify(entry.targetDirectoryUrl)}, import.meta.url);
const library = \`\${process.platform === 'win32' ? '' : 'lib'}${entry.targetName}.\${suffix}\`;

export const rustra = createBunBootstrap({
  libraryName: ${JSON.stringify(entry.targetName)},
  libraryCandidates: [
    fileURLToPath(new URL(\`release/\${library}\`, targetDirectory)),
    fileURLToPath(new URL(\`debug/\${library}\`, targetDirectory)),
  ],
  rkyvV2Codecs: rkyvV2Registry,
  contractHash: GENERATED_CONTRACT_HASH,
  schemaVersion: SCHEMA_VERSION,
});
`;
}

export function generateTauriEntryTs(): string {
  return `// AUTO-GENERATED by @rustra/cli — DO NOT EDIT.
import { createTauriBootstrap } from '@rustra/tauri';

export * from './commands.js';
export { subscribeTauriEvent as subscribeEvent } from '@rustra/tauri';

export const rustra = createTauriBootstrap();
`;
}
