export function templateVersions(cliVersion: string, npmTypesRange: string, cargoRange: string) {
  if (!npmTypesRange.trim() || !cargoRange.trim()) {
    throw new Error('Rustra compatibility ranges must be non-empty');
  }
  return { cargoRange, npmCliCaret: `^${cliVersion}`, npmTypesRange };
}

/**
 * 생성 config 에 심는 $schema 참조 — 배포 패키지(`files` 필드) 루트에 실리는
 * rustra.schema.json 의 상대 경로. URL fetch 없이 에디터가 node_modules 에서 풀어 쓴다.
 */
export const INIT_CONFIG_SCHEMA_PATH = './node_modules/@rustra/cli/rustra.schema.json';

/** init 이 뽑아줄 호스트 섹션 선택 — 감지(detectInitHosts) 또는 --host 로 결정된다. */
export interface InitHosts {
  reactNative: boolean;
}

export interface InitProjectFiles {
  cargoToml: string;
  libRs: string;
  mainRs: string;
  generateRs: string;
  packageJson: string;
  rustraJson: string;
  appTs: string;
  gitignore: string;
  tsconfig: string;
}

/**
 * 최소 config — $schema + schema/output + 호스트 섹션만. codegen/node 바이너리는
 * 명시하지 않으면 CLI 폴백 선택(selectCodegenBinary)이 scaffold 레이아웃에서 정답을 골라
 * 키를 생략해도 doctor/codegen/demo 가 그대로 동작한다(node-only 기준 — RN 변형은
 * Cargo.toml 의 [lib] staticlib 섹션이 짝이 되어야 하며, 아래 libSection 이 담당한다).
 * dev/inspector 는 옵트인이라 기본 템플릿에 넣지 않는다.
 */
export function renderInitProjectFiles(
  v: ReturnType<typeof templateVersions>,
  hosts: InitHosts = { reactNative: false },
): InitProjectFiles {
  // RN 호스트는 staticlib 타깃을 요구한다(selectReactNativeCargoTarget). lib 이름(rustra_app)과
  // bin 이름(rustra-app)은 어긋나 충돌하지 않고, main.rs/bin 의 package() 는 그대로 lib을 링크한다.
  const libSection = hosts.reactNative
    ? `[lib]\nname = "rustra_app"\ncrate-type = ["rlib", "staticlib"]\n\n`
    : '';
  const cargoToml = `# Generated by rustra init — adjust name/edition as needed.\n[package]\nname = "rustra-app"\nversion = "0.1.0"\nedition = "2021"\npublish = false\ndefault-run = "rustra-app"\n\n${libSection}[dependencies]\nrustra = "${v.cargoRange}"\nrustra-macros = "${v.cargoRange}"\nserde = { version = "1", features = ["derive"] }\nserde_json = "1"\nschemars = "0.8"\n\n[[bin]]\nname = "generate"\npath = "src/bin/generate.rs"\n`;
  const libRs = `use rustra::prelude::*;\n\n#[derive(Debug, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]\n#[serde(rename_all = "camelCase")]\npub struct EchoInput {\n    pub message: String,\n}\n\n#[derive(Debug, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]\n#[serde(rename_all = "camelCase")]\npub struct EchoOutput {\n    pub message: String,\n}\n\n#[rustra::command]\nfn echo(input: EchoInput) -> Result<EchoOutput> {\n    Ok(EchoOutput { message: input.message })\n}\n\npub fn package() -> Package {\n    Package::builder("app.demo").command_fn(echo).build()\n}\n`;
  const mainRs = `use serde_json::{json, Value};\nuse std::io::{Read, Write};\n\nfn main() -> rustra::Result<()> {\n    if std::env::args().nth(1).as_deref() == Some("invoke") {\n        return run_invoke_stdio();\n    }\n    let result = rustra_app::package().invoke_json("echo", json!({ "message": "hello from rustra" }))?;\n    println!("{}", result["message"].as_str().unwrap_or_default());\n    Ok(())\n}\n\nfn run_invoke_stdio() -> rustra::Result<()> {\n    let mut input = String::new();\n    std::io::stdin().read_to_string(&mut input)?;\n    let request: Value = serde_json::from_str(&input).map_err(rustra::RustraError::invalid_args)?;\n    let command = request.get("command").and_then(Value::as_str)\n        .ok_or_else(|| rustra::RustraError::invalid_args("missing command"))?;\n    if command == "__rustra_contract" {\n        let hash = rustra_app::package().generate_typescript()?.contract_hash;\n        let response = serde_json::to_vec(&json!({ "ok": true, "result": hash }))\n            .map_err(rustra::RustraError::internal)?;\n        std::io::stdout().write_all(&response)?;\n        return Ok(());\n    }\n    let args = request.get("args").cloned().unwrap_or_else(|| json!({}));\n    let result = rustra_app::package().invoke_json(command, args)?;\n    let response = serde_json::to_vec(&json!({ "ok": true, "result": result }))\n        .map_err(rustra::RustraError::internal)?;\n    std::io::stdout().write_all(&response)?;\n    Ok(())\n}\n`;
  // generate bin 은 codegen --check 의 암묵 계약(cli-codegen.ts)을 지켜야 한다:
  // RUSTRA_SCHEMA_OUT 이 있으면 <env>/schema.json 에 기록(checkRoot 가 임시 디렉터리 —
  // 파일명은 bin 이 붙인다), 없으면 기존처럼 generated/schema.json 에 기록.
  // env 읽기는 var_os — core 의 write_schema_to_dir 와 동일 계약(비-UTF-8 경로 포함).
  // 기록은 발행 API(rustra 0.5+ GeneratedPackage.schema_json) + std fs 로만 —
  // write_schema_to_dir 는 현재 라인에서 발행 보장이 없어 쓰지 않는다.
  const generateRs = `use std::path::PathBuf;\n\nfn main() -> rustra::Result<()> {\n    let generated = rustra_app::package().generate_typescript()?;\n    let out = match std::env::var_os("RUSTRA_SCHEMA_OUT") {\n        Some(p) if !p.is_empty() => PathBuf::from(p).join("schema.json"),\n        _ => PathBuf::from("generated").join("schema.json"),\n    };\n    if let Some(parent) = out.parent() {\n        std::fs::create_dir_all(parent)?;\n    }\n    std::fs::write(&out, generated.schema_json)?;\n    println!("{} written", out.display());\n    Ok(())\n}\n`;
  const packageJson = `{\n  "name": "rustra-app",\n  "private": true,\n  "packageManager": "bun@1.4.0",\n  "type": "module",\n  "scripts": {\n    "doctor": "rustra doctor --config rustra.json",\n    "codegen": "rustra codegen --config rustra.json",\n    "codegen:check": "rustra codegen --config rustra.json --check",\n    "dev": "rustra dev --config rustra.json",\n    "demo": "bun run src/index.ts"\n  },\n  "dependencies": {\n    "@rustra/node": "${v.npmCliCaret}",\n    "@rustra/types": "${v.npmTypesRange}"\n  },\n  "devDependencies": {\n    "@rustra/cli": "${v.npmCliCaret}"\n  }\n}\n`;
  // 키 순서는 $schema 먼저 — 에디터가 스키마를 즉시 묶어 자동완성을 제공하게 한다.
  const configObject: Record<string, unknown> = {
    $schema: INIT_CONFIG_SCHEMA_PATH,
    schema: './generated/schema.json',
    output: './src/generated',
    node: {},
  };
  if (hosts.reactNative) configObject.reactNative = { rustManifest: './Cargo.toml' };
  const rustraJson = `${JSON.stringify(configObject)}\n`;
  const appTs = `import { echo } from './generated/commands.js';\nimport './generated/node.js';\n\nconst result = await echo({ message: 'hello from TypeScript' });\nconsole.log(result.message);\n`;
  const gitignore = `node_modules/\ndist/\ntarget/\n.rustra-codegen/\n`;
  const tsconfig = `{"compilerOptions":{"target":"ES2022","module":"NodeNext","moduleResolution":"NodeNext","strict":true,"esModuleInterop":true,"skipLibCheck":true},"include":["src/**/*.ts"]}\n`;
  return {
    cargoToml,
    libRs,
    mainRs,
    generateRs,
    packageJson,
    rustraJson,
    appTs,
    gitignore,
    tsconfig,
  };
}

export {
  generateBunEntryTs,
  generateNodeEntryTs,
  generateReactNativeEntryTs,
  generateTauriEntryTs,
} from './init-entries.js';
