export function templateVersions(cliVersion: string, npmTypesRange: string, cargoRange: string) {
  if (!npmTypesRange.trim() || !cargoRange.trim()) {
    throw new Error('Rustra compatibility ranges must be non-empty');
  }
  return { cargoRange, npmCliCaret: `^${cliVersion}`, npmTypesRange };
}

export interface InitProjectFiles {
  cargoToml: string;
  libRs: string;
  mainRs: string;
  generateRs: string;
  packageJson: string;
  rustraJson: string;
  appTs: string;
  gitignore: string;
  tsconfig: string;
}

export function renderInitProjectFiles(v: ReturnType<typeof templateVersions>): InitProjectFiles {
  const cargoToml = `# Generated by rustra init — adjust name/edition as needed.\n[package]\nname = "rustra-app"\nversion = "0.1.0"\nedition = "2021"\npublish = false\ndefault-run = "rustra-app"\n\n[dependencies]\nrustra = "${v.cargoRange}"\nrustra-macros = "${v.cargoRange}"\nserde = { version = "1", features = ["derive"] }\nserde_json = "1"\nschemars = "0.8"\n\n[[bin]]\nname = "generate"\npath = "src/bin/generate.rs"\n`;
  const libRs = `use rustra::prelude::*;\n\n#[derive(Debug, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]\n#[serde(rename_all = "camelCase")]\npub struct EchoInput {\n    pub message: String,\n}\n\n#[derive(Debug, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]\n#[serde(rename_all = "camelCase")]\npub struct EchoOutput {\n    pub message: String,\n}\n\n#[rustra::command]\nfn echo(input: EchoInput) -> Result<EchoOutput> {\n    Ok(EchoOutput { message: input.message })\n}\n\npub fn package() -> Package {\n    Package::builder("app.demo").command_fn(echo).build()\n}\n`;
  const mainRs = `use serde_json::{json, Value};\nuse std::io::{Read, Write};\n\nfn main() -> rustra::Result<()> {\n    if std::env::args().nth(1).as_deref() == Some("invoke") {\n        return run_invoke_stdio();\n    }\n    let result = rustra_app::package().invoke_json("echo", json!({ "message": "hello from rustra" }))?;\n    println!("{}", result["message"].as_str().unwrap_or_default());\n    Ok(())\n}\n\nfn run_invoke_stdio() -> rustra::Result<()> {\n    let mut input = String::new();\n    std::io::stdin().read_to_string(&mut input)?;\n    let request: Value = serde_json::from_str(&input).map_err(rustra::RustraError::invalid_args)?;\n    let command = request.get("command").and_then(Value::as_str)\n        .ok_or_else(|| rustra::RustraError::invalid_args("missing command"))?;\n    if command == "__rustra_contract" {\n        let hash = rustra_app::package().generate_typescript()?.contract_hash;\n        let response = serde_json::to_vec(&json!({ "ok": true, "result": hash }))\n            .map_err(rustra::RustraError::internal)?;\n        std::io::stdout().write_all(&response)?;\n        return Ok(());\n    }\n    let args = request.get("args").cloned().unwrap_or_else(|| json!({}));\n    let result = rustra_app::package().invoke_json(command, args)?;\n    let response = serde_json::to_vec(&json!({ "ok": true, "result": result }))\n        .map_err(rustra::RustraError::internal)?;\n    std::io::stdout().write_all(&response)?;\n    Ok(())\n}\n`;
  const generateRs = `fn main() -> rustra::Result<()> {\n    let generated = rustra_app::package().generate_typescript()?;\n    generated.write_to_dir("generated")?;\n    println!("generated/schema.json written");\n    Ok(())\n}\n`;
  const packageJson = `{\n  "name": "rustra-app",\n  "private": true,\n  "packageManager": "bun@1.4.0",\n  "type": "module",\n  "scripts": {\n    "doctor": "rustra doctor --config rustra.json",\n    "codegen": "rustra codegen --config rustra.json",\n    "codegen:check": "rustra codegen --config rustra.json --check",\n    "dev": "rustra dev --config rustra.json",\n    "demo": "bun run src/index.ts"\n  },\n  "dependencies": {\n    "@rustra/node": "${v.npmCliCaret}",\n    "@rustra/types": "${v.npmTypesRange}"\n  },\n  "devDependencies": {\n    "@rustra/cli": "${v.npmCliCaret}"\n  }\n}\n`;
  const rustraJson = `{"schema":"./generated/schema.json","output":"./src/generated","codegen":{"rustManifest":"./Cargo.toml","rustBinary":"generate"},"node":{"rustManifest":"./Cargo.toml","rustBinary":"rustra-app"}}\n`;
  const appTs = `import { echo } from './generated/commands.js';\nimport './generated/node.js';\n\nconst result = await echo({ message: 'hello from TypeScript' });\nconsole.log(result.message);\n`;
  const gitignore = `node_modules/\ndist/\ntarget/\n.rustra-codegen/\n`;
  const tsconfig = `{"compilerOptions":{"target":"ES2022","module":"NodeNext","moduleResolution":"NodeNext","strict":true,"esModuleInterop":true,"skipLibCheck":true},"include":["src/**/*.ts"]}\n`;
  return {
    cargoToml,
    libRs,
    mainRs,
    generateRs,
    packageJson,
    rustraJson,
    appTs,
    gitignore,
    tsconfig,
  };
}

export {
  generateBunEntryTs,
  generateNodeEntryTs,
  generateReactNativeEntryTs,
  generateTauriEntryTs,
} from './init-entries.js';
