import { readFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { sha256 } from './hash.js';
import { toPosixPath } from './paths.js';

export type GeneratedFile = {
  path: string;
  content: string;
};

export interface GeneratedManifest {
  schemaVersion: 1;
  schemaHash: string;
  generatorVersion: string;
  files: Array<{ path: string; sha256: string }>;
}

export function manifestPathFor(root: string, target: string): string {
  return toPosixPath(relative(root, target)) || '.';
}

/** Build the sidecar that lets CI detect stale generated code without writing files. */
export function buildGeneratedManifest(
  schemaContent: string,
  generatorVersion: string,
  files: GeneratedFile[],
): GeneratedManifest {
  return {
    schemaVersion: 1,
    schemaHash: sha256(schemaContent),
    generatorVersion,
    files: files
      .map((file) => ({ path: toPosixPath(file.path), sha256: sha256(file.content) }))
      .sort((left, right) => left.path.localeCompare(right.path)),
  };
}

/** Verify generated bytes against the sidecar and the current generator output. */
export async function checkGeneratedFiles(
  files: GeneratedFile[],
  manifestPath: string,
  metadata?: { schemaContent?: string; generatorVersion?: string },
): Promise<void> {
  const manifestRoot = dirname(resolve(manifestPath));
  let manifest: GeneratedManifest;
  try {
    manifest = JSON.parse(await readFile(manifestPath, 'utf8')) as GeneratedManifest;
  } catch (error) {
    throw new Error(`Generated drift (missing): ${manifestPath}. Run rustra codegen first.`, {
      cause: error,
    });
  }

  if (
    manifest.schemaVersion !== 1 ||
    typeof manifest.schemaHash !== 'string' ||
    !Array.isArray(manifest.files)
  ) {
    throw new Error(`Generated drift (invalid manifest): ${manifestPath}`);
  }
  if (
    metadata?.schemaContent !== undefined &&
    manifest.schemaHash !== sha256(metadata.schemaContent)
  ) {
    throw new Error('Generated drift (schema changed): schema.json');
  }
  if (
    metadata?.generatorVersion !== undefined &&
    manifest.generatorVersion !== metadata.generatorVersion
  ) {
    throw new Error(
      `Generated drift (generator changed): ${manifest.generatorVersion} -> ${metadata.generatorVersion}`,
    );
  }

  const expected = new Map(
    files.map((file) => [
      manifestPathFor(manifestRoot, resolve(file.path)),
      { path: resolve(file.path), content: file.content },
    ]),
  );
  const recorded = new Map(manifest.files.map((file) => [file.path, file]));
  const inspected = await Promise.all(
    [...expected].map(async ([path, file]) => {
      const recordedFile = recorded.get(path);
      if (!recordedFile) {
        throw new Error(`Generated drift (missing manifest entry): ${path}`);
      }
      let actual: string;
      try {
        actual = await readFile(file.path, 'utf8');
      } catch {
        throw new Error(`Generated drift (missing): ${path}`);
      }
      return { path, file, actual, recordedFile };
    }),
  );
  for (const { path, file, actual, recordedFile } of inspected) {
    if (actual !== file.content) throw new Error(`Generated drift (disk changed): ${path}`);
    if (sha256(file.content) !== recordedFile.sha256) {
      throw new Error(`Generated drift (manifest stale): ${path}`);
    }
  }
  for (const path of recorded.keys()) {
    if (!expected.has(path)) {
      throw new Error(`Generated drift (unexpected): ${path}`);
    }
  }
}
