/** Conservative source discovery only; user Rust files are never rewritten. */
export function packageFactories(source: string): string[] {
  let code = '';
  for (let i = 0; i < source.length;) {
    const rest = source.slice(i);
    let end = i;
    if (rest.startsWith('//')) {
      end = source.indexOf('\n', i);
      if (end === -1) end = source.length;
    } else if (rest.startsWith('/*')) {
      let depth = 1;
      end = i + 2;
      while (depth && end < source.length) {
        if (source.startsWith('/*', end)) {
          depth++;
          end += 2;
        } else if (source.startsWith('*/', end)) {
          depth--;
          end += 2;
        } else end++;
      }
    } else {
      const raw = /^(?:br|r)(#*)"/.exec(rest);
      const char = /^'(?:\\.|[^\\'\n])'/.exec(rest);
      if (raw) {
        const close = source.indexOf(`"${raw[1]}`, i + raw[0].length);
        end = close === -1 ? source.length : close + 1 + raw[1]!.length;
      } else if (char) end = i + char[0].length;
      else if (source[i] === '"') {
        end = i + 1;
        while (end < source.length) {
          if (source[end] === '\\') end += 2;
          else if (source[end++] === '"') break;
        }
      }
    }
    if (end > i) {
      code += ' '.repeat(end - i);
      i = end;
    } else code += source[i++]!;
  }
  const factories: string[] = [];
  let depth = 0;
  let scanned = 0;
  for (const match of code.matchAll(
    /\bpub\s+fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(\s*\)\s*->\s*(?:(?:rustra|crate)::)?Package\b/g,
  )) {
    for (; scanned < match.index; scanned++) {
      if (code[scanned] === '{') depth++;
      else if (code[scanned] === '}') depth--;
    }
    if (depth === 0) factories.push(match[1]!);
  }
  return factories;
}

export function renderTauriRegistration(producer: string): string {
  return `// Generated by rustra setup. Matching Rustra development source is required until released.\n// Add \`mod rustra_setup;\` to the native entry. Preserve plugins/state on the builder.\n\npub fn register<R: tauri::Runtime>(builder: tauri::Builder<R>) -> tauri::Builder<R> {\n    rustra::tauri_support::register_with_events(${producer}(), builder)\n}\n\n// Use this instead of .invoke_handler(...) when the app also has native commands.\n// This must be the final handler installation; Rustra's production endpoints take precedence.\npub fn with_app_commands<R, F>(builder: tauri::Builder<R>, app_handler: F) -> tauri::Builder<R>\nwhere\n    R: tauri::Runtime,\n    F: Fn(tauri::ipc::Invoke<R>) -> bool + Send + Sync + 'static,\n{\n    rustra::tauri_support::with_app_commands(register(builder), app_handler)\n}\n`;
}
