# rustra runner 템플릿 iOS Podfile.
# Lynx 엔진 + 서비스는 CocoaPods source pod (pod install 시 소스 컴파일).
# RustraLynx 로컬 pod 가 Rust staticlib + RustraModule(LynxModule) 을 링크/등록.
# 스파이크 examples/lynx-calculator/ios/Podfile 에서 정제 추출.
platform :ios, '14.0'

target 'RustraTemplate' do
  use_frameworks!
  pod 'Lynx'
  pod 'LynxService'
  pod 'RustraLynx', :path => 'modules/rustra-lynx'
end

# Xcode 26 호환 (Lynx pod 가 warnings-as-errors 로 실패하지 않도록).
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      config.build_settings['USER_SCRIPT_SANDBOXING'] = 'NO'
      disable = ['-Wno-error', '-Wno-c99-designator',
                 '-Wno-deprecated-declarations', '-Wno-deprecated-implementations']
      ['OTHER_CPLUSPLUSFLAGS', 'OTHER_CFLAGS'].each do |key|
        flags = config.build_settings[key] || ['$(inherited)']
        flags = [flags] unless flags.is_a?(Array)
        config.build_settings[key] = flags + disable
      end
    end
  end
end
