// AUTO-GENERATED by @rustra/cli — DO NOT EDIT.
// C++ postcard codec for the RN JSI fast path (B1).
#include "rustra-generated-codecs.hpp"
#include <jsi/jsi.h>
#include <string>

using namespace facebook::jsi;
namespace rc = rustra::codec;

static void encode_addNumbers(jsi::Runtime& rt, const jsi::Value& args, rc::Writer& w) {
  w.push_u8(1); w.push_u8(0); // cmd_id = 1 LE
  auto argsObj = args.asObject(rt);
  { auto _v = argsObj.getProperty(rt, "a").asNumber(); w.push_i64((int64_t)_v); }
  { auto _v = argsObj.getProperty(rt, "b").asNumber(); w.push_i64((int64_t)_v); }
}

static jsi::Value decode_addNumbers(jsi::Runtime& rt, rc::Reader& r) {
  auto resultObj = jsi::Object(rt);
  resultObj.setProperty(rt, "value", (double)r.read_i64());
  return std::move(resultObj);
}

static void encode_clamp(jsi::Runtime& rt, const jsi::Value& args, rc::Writer& w) {
  w.push_u8(4); w.push_u8(0); // cmd_id = 4 LE
  auto argsObj = args.asObject(rt);
  { auto _v = argsObj.getProperty(rt, "max").asNumber(); w.push_f64(_v); }
  { auto _v = argsObj.getProperty(rt, "min").asNumber(); w.push_f64(_v); }
  { auto _v = argsObj.getProperty(rt, "value").asNumber(); w.push_f64(_v); }
}

static jsi::Value decode_clamp(jsi::Runtime& rt, rc::Reader& r) {
  auto resultObj = jsi::Object(rt);
  resultObj.setProperty(rt, "value", r.read_f64());
  return std::move(resultObj);
}

static void encode_createItem(jsi::Runtime& rt, const jsi::Value& args, rc::Writer& w) {
  w.push_u8(8); w.push_u8(0); // cmd_id = 8 LE
  auto argsObj = args.asObject(rt);
  { auto _v = argsObj.getProperty(rt, "name").getString(rt).utf8(rt); w.push_string(_v); }
  { auto _v = argsObj.getProperty(rt, "value").asNumber(); w.push_i64((int64_t)_v); }
}

static jsi::Value decode_createItem(jsi::Runtime& rt, rc::Reader& r) {
  auto resultObj = jsi::Object(rt);
  { auto _obj = jsi::Object(rt);
    _obj.setProperty(rt, "active", r.read_bool());
    { auto _s = r.read_string(); _obj.setProperty(rt, "name", jsi::String::createFromUtf8(rt, reinterpret_cast<const uint8_t*>(_s.data()), _s.size())); }
    _obj.setProperty(rt, "value", (double)r.read_i64());
    resultObj.setProperty(rt, "item", _obj); }
  return std::move(resultObj);
}

static void encode_greet(jsi::Runtime& rt, const jsi::Value& args, rc::Writer& w) {
  w.push_u8(5); w.push_u8(0); // cmd_id = 5 LE
  auto argsObj = args.asObject(rt);
  { auto _v = argsObj.getProperty(rt, "name").getString(rt).utf8(rt); w.push_string(_v); }
}

static jsi::Value decode_greet(jsi::Runtime& rt, rc::Reader& r) {
  auto resultObj = jsi::Object(rt);
  { auto _s = r.read_string(); resultObj.setProperty(rt, "message", jsi::String::createFromUtf8(rt, reinterpret_cast<const uint8_t*>(_s.data()), _s.size())); }
  return std::move(resultObj);
}

static void encode_isEven(jsi::Runtime& rt, const jsi::Value& args, rc::Writer& w) {
  w.push_u8(3); w.push_u8(0); // cmd_id = 3 LE
  auto argsObj = args.asObject(rt);
  { auto _v = argsObj.getProperty(rt, "n").asNumber(); w.push_i64((int64_t)_v); }
}

static jsi::Value decode_isEven(jsi::Runtime& rt, rc::Reader& r) {
  auto resultObj = jsi::Object(rt);
  resultObj.setProperty(rt, "result", r.read_bool());
  return std::move(resultObj);
}

static void encode_multiply(jsi::Runtime& rt, const jsi::Value& args, rc::Writer& w) {
  w.push_u8(2); w.push_u8(0); // cmd_id = 2 LE
  auto argsObj = args.asObject(rt);
  { auto _v = argsObj.getProperty(rt, "a").asNumber(); w.push_f64(_v); }
  { auto _v = argsObj.getProperty(rt, "b").asNumber(); w.push_f64(_v); }
}

static jsi::Value decode_multiply(jsi::Runtime& rt, rc::Reader& r) {
  auto resultObj = jsi::Object(rt);
  resultObj.setProperty(rt, "value", r.read_f64());
  return std::move(resultObj);
}

static void encode_processItem(jsi::Runtime& rt, const jsi::Value& args, rc::Writer& w) {
  w.push_u8(9); w.push_u8(0); // cmd_id = 9 LE
  auto argsObj = args.asObject(rt);
  { auto _v = argsObj.getProperty(rt, "item").asObject(rt).getProperty(rt, "active").getBool(); w.push_bool(_v); }
  { auto _v = argsObj.getProperty(rt, "item").asObject(rt).getProperty(rt, "name").getString(rt).utf8(rt); w.push_string(_v); }
  { auto _v = argsObj.getProperty(rt, "item").asObject(rt).getProperty(rt, "value").asNumber(); w.push_i64((int64_t)_v); }
}

static jsi::Value decode_processItem(jsi::Runtime& rt, rc::Reader& r) {
  auto resultObj = jsi::Object(rt);
  resultObj.setProperty(rt, "doubled", r.read_bool());
  { auto _obj = jsi::Object(rt);
    _obj.setProperty(rt, "active", r.read_bool());
    { auto _s = r.read_string(); _obj.setProperty(rt, "name", jsi::String::createFromUtf8(rt, reinterpret_cast<const uint8_t*>(_s.data()), _s.size())); }
    _obj.setProperty(rt, "value", (double)r.read_i64());
    resultObj.setProperty(rt, "item", _obj); }
  return std::move(resultObj);
}

static void encode_rustraRegistryDemo(jsi::Runtime& rt, const jsi::Value& args, rc::Writer& w) {
  w.push_u8(10); w.push_u8(0); // cmd_id = 10 LE
  auto argsObj = args.asObject(rt);
  { auto _v = argsObj.getProperty(rt, "op").getString(rt).utf8(rt); w.push_string(_v); }
}

static jsi::Value decode_rustraRegistryDemo(jsi::Runtime& rt, rc::Reader& r) {
  auto resultObj = jsi::Object(rt);
  resultObj.setProperty(rt, "ok", r.read_bool());
  resultObj.setProperty(rt, "frozen", r.read_bool());
  { auto _s = r.read_string(); resultObj.setProperty(rt, "message", jsi::String::createFromUtf8(rt, reinterpret_cast<const uint8_t*>(_s.data()), _s.size())); }
  return std::move(resultObj);
}

static void encode_sumList(jsi::Runtime& rt, const jsi::Value& args, rc::Writer& w) {
  w.push_u8(6); w.push_u8(0); // cmd_id = 6 LE
  auto argsObj = args.asObject(rt);
  { auto _arr = argsObj.getProperty(rt, "numbers").asObject(rt).getArray(rt); auto _n = _arr.length(rt); w.push_uvar(_n); for (size_t _i = 0; _i < _n; _i++) { auto _e = _arr.getValueAtIndex(rt, _i).asNumber(); w.push_i64((int64_t)_e); } }
}

static jsi::Value decode_sumList(jsi::Runtime& rt, rc::Reader& r) {
  auto resultObj = jsi::Object(rt);
  resultObj.setProperty(rt, "count", (double)r.read_i64());
  resultObj.setProperty(rt, "total", (double)r.read_i64());
  return std::move(resultObj);
}

static void encode_toUpper(jsi::Runtime& rt, const jsi::Value& args, rc::Writer& w) {
  w.push_u8(7); w.push_u8(0); // cmd_id = 7 LE
  auto argsObj = args.asObject(rt);
  { auto _v = argsObj.getProperty(rt, "s").getString(rt).utf8(rt); w.push_string(_v); }
}

static jsi::Value decode_toUpper(jsi::Runtime& rt, rc::Reader& r) {
  auto resultObj = jsi::Object(rt);
  { auto _s = r.read_string(); resultObj.setProperty(rt, "result", jsi::String::createFromUtf8(rt, reinterpret_cast<const uint8_t*>(_s.data()), _s.size())); }
  return std::move(resultObj);
}

namespace rustra::generated {

bool encode_by_name(Runtime& rt, const std::string& name, const Value& args, rc::Writer& w) {
  if (name == "addNumbers") { encode_addNumbers(rt, args, w); return true; }
  if (name == "clamp") { encode_clamp(rt, args, w); return true; }
  if (name == "createItem") { encode_createItem(rt, args, w); return true; }
  if (name == "greet") { encode_greet(rt, args, w); return true; }
  if (name == "isEven") { encode_isEven(rt, args, w); return true; }
  if (name == "multiply") { encode_multiply(rt, args, w); return true; }
  if (name == "processItem") { encode_processItem(rt, args, w); return true; }
  if (name == "rustraRegistryDemo") { encode_rustraRegistryDemo(rt, args, w); return true; }
  if (name == "sumList") { encode_sumList(rt, args, w); return true; }
  if (name == "toUpper") { encode_toUpper(rt, args, w); return true; }
  return false; // 동적 명령 — JS 가 Tier 3 fallback 처리
}

Value decode_by_name(Runtime& rt, const std::string& name, rc::Reader& r) {
  if (name == "addNumbers") return decode_addNumbers(rt, r);
  if (name == "clamp") return decode_clamp(rt, r);
  if (name == "createItem") return decode_createItem(rt, r);
  if (name == "greet") return decode_greet(rt, r);
  if (name == "isEven") return decode_isEven(rt, r);
  if (name == "multiply") return decode_multiply(rt, r);
  if (name == "processItem") return decode_processItem(rt, r);
  if (name == "rustraRegistryDemo") return decode_rustraRegistryDemo(rt, r);
  if (name == "sumList") return decode_sumList(rt, r);
  if (name == "toUpper") return decode_toUpper(rt, r);
  throw JSError(rt, "rustra: no C++ codec for '" + name + "'");
}

bool has_static_codec(const std::string& name) {
  if (name == "addNumbers") return true;
  if (name == "clamp") return true;
  if (name == "createItem") return true;
  if (name == "greet") return true;
  if (name == "isEven") return true;
  if (name == "multiply") return true;
  if (name == "processItem") return true;
  if (name == "rustraRegistryDemo") return true;
  if (name == "sumList") return true;
  if (name == "toUpper") return true;
  return false;
}

} // namespace rustra::generated
